namespace Autodor.Modules.Invoicing.Domain.ValueObjects;

/// <summary>
/// Represents an invoice data structure for external invoicing systems integration.
/// This record serves as an immutable container for invoice information that will be
/// transmitted to external invoice providers (iFirma, inFakt) for invoice generation.
/// The invoice is not persisted in the local database - it exists only as a data transfer object.
/// </summary>
/// <param name="Number">Invoice number, may be null if auto-generated by external system</param>
/// <param name="IssueDate">Date when the invoice was issued</param>
/// <param name="SaleDate">Date when the sale transaction occurred</param>
/// <param name="PaymentDue">Due date for payment</param>
/// <param name="PaymentMethod">Method of payment (e.g., "transfer", "cash", "card")</param>
/// <param name="PlaceOfIssue">Location where the invoice was issued</param>
/// <param name="Notes">Additional notes or comments for the invoice</param>
/// <param name="Contractor">Contractor information formatted for invoice purposes</param>
/// <param name="Items">Collection of items included in this invoice</param>
public record Invoice(
    int? Number,
    DateTime IssueDate,
    DateTime SaleDate,
    DateTime PaymentDue,
    string PaymentMethod,
    string PlaceOfIssue,
    string Notes,
    Contractor Contractor,
    IReadOnlyList<InvoiceItem> Items
)
{
    /// <summary>
    /// Gets the total net amount (before VAT) for all items in the invoice.
    /// </summary>
    public decimal TotalNet => Items.Sum(i => i.TotalNet);
    
    /// <summary>
    /// Gets the total VAT amount for all items in the invoice.
    /// </summary>
    public decimal TotalVat => Items.Sum(i => i.VatAmount);
    
    /// <summary>
    /// Gets the total gross amount (including VAT) for all items in the invoice.
    /// </summary>
    public decimal TotalGross => Items.Sum(i => i.TotalGross);
};