/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../axios';
import type { ApplicationInfoDto } from '../models';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApplicationInformation = (options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<ApplicationInfoDto>({ url: `/api/Abouts`, method: 'GET', signal }, options);
};

export const getGetApplicationInformationQueryKey = () => {
  return [`/api/Abouts`] as const;
};

export const getGetApplicationInformationQueryOptions = <
  TData = Awaited<ReturnType<typeof getApplicationInformation>>,
  TError = unknown
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationInformation>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApplicationInformationQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationInformation>>> = ({ signal }) =>
    getApplicationInformation(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApplicationInformation>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetApplicationInformationQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationInformation>>>;
export type GetApplicationInformationQueryError = unknown;

export function useGetApplicationInformation<
  TData = Awaited<ReturnType<typeof getApplicationInformation>>,
  TError = unknown
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationInformation>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationInformation>>,
          TError,
          Awaited<ReturnType<typeof getApplicationInformation>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetApplicationInformation<
  TData = Awaited<ReturnType<typeof getApplicationInformation>>,
  TError = unknown
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationInformation>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationInformation>>,
          TError,
          Awaited<ReturnType<typeof getApplicationInformation>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetApplicationInformation<
  TData = Awaited<ReturnType<typeof getApplicationInformation>>,
  TError = unknown
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationInformation>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useGetApplicationInformation<
  TData = Awaited<ReturnType<typeof getApplicationInformation>>,
  TError = unknown
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationInformation>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetApplicationInformationQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
