/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const printInvoiceBody = zod.object({
  orderId: zod.string().min(1),
  date: zod.string().datetime({ offset: true }).optional()
});

export const printInvoiceResponse = zod.instanceof(File);

export const createInvoiceBody = zod.object({
  invoiceNumber: zod.number().nullish(),
  saleDate: zod.string().datetime({ offset: true }).optional(),
  issueDate: zod.string().datetime({ offset: true }).optional(),
  dates: zod.array(zod.string().datetime({ offset: true })).min(1),
  orderIds: zod.array(zod.string()).min(1),
  contractorId: zod.number()
});

export const createInvoiceResponse = zod.object({
  customerNumber: zod.string().nullish(),
  response: zod
    .object({
      kod: zod.number().optional(),
      informacja: zod.string().nullish()
    })
    .optional()
});
