/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import { z as zod } from 'zod';

export const getOrdersQueryParams = zod.object({
  dateFrom: zod.string().datetime({ offset: true }),
  dateTo: zod.string().datetime({ offset: true })
});

export const getOrdersResponseItem = zod.object({
  isExcluded: zod.boolean().optional(),
  date: zod.string().datetime({ offset: true }).optional(),
  id: zod.string().nullish(),
  number: zod.string().nullish(),
  person: zod.string().nullish(),
  customerNumber: zod.string().nullish(),
  items: zod
    .array(
      zod.object({
        partNumber: zod.string().nullish(),
        partName: zod.string().nullish(),
        quantity: zod.number().optional(),
        totalPrice: zod.number().optional()
      })
    )
    .nullish(),
  itemsCount: zod.number().optional(),
  totalPrice: zod.number().optional()
});
export const getOrdersResponse = zod.array(getOrdersResponseItem);

export const excludeOrderBody = zod.object({
  orderId: zod.string().min(1)
});
