/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * GET_api_system_version
 * @summary Get API version and build information
 */
export const GetVersionResponse = zod.object({
  "sha": zod.string().nullable()
})

