/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Get the application health status.
 */
export const GetApplicationHealthResponse = zod.object({
  "status": zod.string()
})

/**
 * @summary Get the application liveness status.
 */
export const GetApplicationAlivenessResponse = zod.object({
  "status": zod.string()
})
