/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Returns the aggregated health status of the application and its dependencies.
 * @summary Get the application health status.
 */
export const GetApplicationHealthResponse = zod.object({
	status: zod.string(),
});

/**
 * Returns the application's liveness status based on its self check.
 * @summary Get the application liveness status.
 */
export const GetApplicationAlivenessResponse = zod.object({
	status: zod.string(),
});

/**
 * Returns the source revision used to build the application.
 * @summary Get the application version.
 */
export const GetVersionResponse = zod.object({
	sha: zod.string(),
});
