/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import type { BuildInformation } from './buildInformation';

export interface ApplicationInfoDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  version?: string | null;
  buildInfo?: BuildInformation;
}
