/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import type { BaseEvent } from './baseEvent';

export interface Contractor {
  /** @nullable */
  city?: string | null;
  created?: string;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  readonly domainEvents?: readonly BaseEvent[] | null;
  /** @nullable */
  email?: string | null;
  id?: number;
  lastModified?: string;
  /** @nullable */
  lastModifiedBy?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nip?: string | null;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  zipCode?: string | null;
}
