/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import type { Contractor } from './contractor';
import type { OrderDto } from './orderDto';

export interface CreateInvoiceCommand {
  /** @nullable */
  invoiceNumber?: number | null;
  saleDate?: string;
  issueDate?: string;
  /** @minItems 1 */
  orders: OrderDto[];
  contractor?: Contractor;
}
