/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */

export interface CreateInvoiceCommand {
  /** @nullable */
  invoiceNumber?: number | null;
  saleDate?: string;
  issueDate?: string;
  /** @minItems 1 */
  dates: string[];
  /** @minItems 1 */
  orderIds: string[];
  contractorId: number;
}
