/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */

export interface CreateContractorCommand {
  /** @minLength 1 */
  city: string;
  /** @nullable */
  email?: string | null;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  nip: string;
  /** @minLength 1 */
  street: string;
  /** @minLength 1 */
  zipCode: string;
}
