/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */

export interface ExcludeOrderPositionCommand {
  /** @nullable */
  orderId?: string | null;
  /** @nullable */
  partNumber?: string | null;
}
