/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */
import type { ResponseDto } from './responseDto';

export interface InvoiceResponseDto {
  /** @nullable */
  customerNumber?: string | null;
  response?: ResponseDto;
}
