/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */

export interface OrderItem {
  /** @nullable */
  partName?: string | null;
  /** @nullable */
  partNumber?: string | null;
  quantity?: number;
  totalPrice?: number;
}
