/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */

export interface StringResult {
  readonly isSuccess?: boolean;
  /** @nullable */
  readonly value?: string | null;
  /** @nullable */
  readonly error?: string | null;
}
