/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Web
 * OpenAPI spec version: 1.0
 */

export interface UpdateContractorCommand {
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  city: string;
  /** @minLength 1 */
  nip: string;
  /** @minLength 1 */
  zipCode: string;
  /** @minLength 1 */
  street: string;
  /** @nullable */
  email?: string | null;
}
