/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type CreateValidationModelErrorParams = {
Name?: string;
Email?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Quantity: number | string;
};
