/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ManualInvoiceItem } from "./manualInvoiceItem";

export interface CreateManualInvoiceCommand {
	/**
	 * @nullable
	 * @pattern ^-?(?:0|[1-9]\d*)$
	 */
	invoiceNumber: number | string | null;
	saleDate: string;
	issueDate: string;
	contractorNIP: string;
	items: ManualInvoiceItem[];
}
