/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ManualInvoiceItem {
	itemNumber: string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	quantity: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
	netUnitPrice: number | string;
}
