/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateInvoiceCommand {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  invoiceNumber: number | string | null;
  saleDate: string;
  issueDate: string;
  dates: string[];
  orderIds: string[];
  contractorNip: string;
}
