/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateContractorCommand {
  id: string;
  nip: string;
  name: string;
  street: string;
  city: string;
  zipCode: string;
  email: string;
}
