/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * PUT_api_contractors_id
 * @summary Update contractor details
 */
export const UpdateContractorParams = zod.object({
  "id": zod.string()
})

export const UpdateContractorBody = zod.object({
  "nip": zod.string(),
  "name": zod.string(),
  "street": zod.string(),
  "city": zod.string(),
  "zipCode": zod.string(),
  "email": zod.string()
})

/**
 * GET_api_contractors_id
 * @summary Get contractor by ID
 */
export const GetContractorParams = zod.object({
  "id": zod.uuid()
})

export const GetContractorResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "nip": zod.string(),
  "street": zod.string(),
  "city": zod.string(),
  "zipCode": zod.string(),
  "email": zod.string()
})

/**
 * DELETE_api_contractors_id
 * @summary Delete contractor
 */
export const DeleteContractorParams = zod.object({
  "id": zod.uuid()
})

/**
 * GET_api_contractors
 * @summary Get all contractors, optionally filtered by NIPs
 */
export const GetContractorsQueryParams = zod.object({
  "nips": zod.array(zod.string()).optional()
})

export const GetContractorsResponseItem = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "nip": zod.string(),
  "street": zod.string(),
  "city": zod.string(),
  "zipCode": zod.string(),
  "email": zod.string()
})
export const GetContractorsResponse = zod.array(GetContractorsResponseItem)

/**
 * POST_api_contractors
 * @summary Create a new contractor
 */
export const CreateContractorBody = zod.object({
  "name": zod.string(),
  "nip": zod.string(),
  "street": zod.string(),
  "city": zod.string(),
  "zipCode": zod.string(),
  "email": zod.string()
})

export const CreateContractorResponse = zod.object({
  "id": zod.uuid()
})

