/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateContractorCommand,
  CreateContractorResponse,
  GetContractorResponse,
  GetContractorsParams,
  GetContractorsResponse,
  ProblemDetails,
  UpdateContractorCommand
} from '../models';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type updateContractorResponse204 = {
  data: unknown
  status: 204
}

export type updateContractorResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 204>
}

export type updateContractorResponseSuccess = (updateContractorResponse204) & {
  headers: Headers;
};
export type updateContractorResponseError = (updateContractorResponseDefault) & {
  headers: Headers;
};

export type updateContractorResponse = (updateContractorResponseSuccess | updateContractorResponseError)

export const getUpdateContractorUrl = (id: string,) => {




  return `/contractors/${id}`
}

/**
 * PUT_contractors_id
 * @summary Update contractor details
 */
export const updateContractor = async (id: string,
    updateContractorCommand: UpdateContractorCommand, options?: RequestInit): Promise<updateContractorResponse> => {

  const res = await fetch(getUpdateContractorUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateContractorCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateContractorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateContractorResponse
}




export const getUpdateContractorMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContractor>>, TError,{id: string;data: UpdateContractorCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateContractor>>, TError,{id: string;data: UpdateContractorCommand}, TContext> => {

const mutationKey = ['updateContractor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContractor>>, {id: string;data: UpdateContractorCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  updateContractor(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateContractorMutationResult = NonNullable<Awaited<ReturnType<typeof updateContractor>>>
    export type UpdateContractorMutationBody = UpdateContractorCommand
    export type UpdateContractorMutationError = ProblemDetails

    /**
 * @summary Update contractor details
 */
export const useUpdateContractor = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContractor>>, TError,{id: string;data: UpdateContractorCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContractor>>,
        TError,
        {id: string;data: UpdateContractorCommand},
        TContext
      > => {
      return useMutation(getUpdateContractorMutationOptions(options), queryClient);
    }
    export type getContractorResponse200 = {
  data: GetContractorResponse
  status: 200
}

export type getContractorResponse404 = {
  data: unknown
  status: 404
}

export type getContractorResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type getContractorResponseSuccess = (getContractorResponse200) & {
  headers: Headers;
};
export type getContractorResponseError = (getContractorResponse404 | getContractorResponseDefault) & {
  headers: Headers;
};

export type getContractorResponse = (getContractorResponseSuccess | getContractorResponseError)

export const getGetContractorUrl = (id: string,) => {




  return `/contractors/${id}`
}

/**
 * GET_contractors_id
 * @summary Get contractor by ID
 */
export const getContractor = async (id: string, options?: RequestInit): Promise<getContractorResponse> => {

  const res = await fetch(getGetContractorUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getContractorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getContractorResponse
}





export const getGetContractorQueryKey = (id: string,) => {
    return [
    `/contractors/${id}`
    ] as const;
    }


export const getGetContractorQueryOptions = <TData = Awaited<ReturnType<typeof getContractor>>, TError = unknown | ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContractorQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContractor>>> = ({ signal }) => getContractor(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContractorQueryResult = NonNullable<Awaited<ReturnType<typeof getContractor>>>
export type GetContractorQueryError = unknown | ProblemDetails


export function useGetContractor<TData = Awaited<ReturnType<typeof getContractor>>, TError = unknown | ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContractor>>,
          TError,
          Awaited<ReturnType<typeof getContractor>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContractor<TData = Awaited<ReturnType<typeof getContractor>>, TError = unknown | ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContractor>>,
          TError,
          Awaited<ReturnType<typeof getContractor>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContractor<TData = Awaited<ReturnType<typeof getContractor>>, TError = unknown | ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get contractor by ID
 */

export function useGetContractor<TData = Awaited<ReturnType<typeof getContractor>>, TError = unknown | ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContractorQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteContractorResponse204 = {
  data: unknown
  status: 204
}

export type deleteContractorResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteContractorResponseSuccess = (deleteContractorResponse204) & {
  headers: Headers;
};
export type deleteContractorResponseError = (deleteContractorResponseDefault) & {
  headers: Headers;
};

export type deleteContractorResponse = (deleteContractorResponseSuccess | deleteContractorResponseError)

export const getDeleteContractorUrl = (id: string,) => {




  return `/contractors/${id}`
}

/**
 * DELETE_contractors_id
 * @summary Delete contractor
 */
export const deleteContractor = async (id: string, options?: RequestInit): Promise<deleteContractorResponse> => {

  const res = await fetch(getDeleteContractorUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteContractorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteContractorResponse
}




export const getDeleteContractorMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContractor>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContractor>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteContractor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContractor>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteContractor(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContractorMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContractor>>>

    export type DeleteContractorMutationError = ProblemDetails

    /**
 * @summary Delete contractor
 */
export const useDeleteContractor = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContractor>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteContractor>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteContractorMutationOptions(options), queryClient);
    }
    export type getContractorsResponse200 = {
  data: GetContractorsResponse[]
  status: 200
}

export type getContractorsResponse404 = {
  data: unknown
  status: 404
}

export type getContractorsResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type getContractorsResponseSuccess = (getContractorsResponse200) & {
  headers: Headers;
};
export type getContractorsResponseError = (getContractorsResponse404 | getContractorsResponseDefault) & {
  headers: Headers;
};

export type getContractorsResponse = (getContractorsResponseSuccess | getContractorsResponseError)

export const getGetContractorsUrl = (params?: GetContractorsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/contractors?${stringifiedParams}` : `/contractors`
}

/**
 * GET_contractors
 * @summary Get all contractors, optionally filtered by NIPs
 */
export const getContractors = async (params?: GetContractorsParams, options?: RequestInit): Promise<getContractorsResponse> => {

  const res = await fetch(getGetContractorsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getContractorsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getContractorsResponse
}





export const getGetContractorsQueryKey = (params?: GetContractorsParams,) => {
    return [
    `/contractors`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetContractorsQueryOptions = <TData = Awaited<ReturnType<typeof getContractors>>, TError = unknown | ProblemDetails>(params?: GetContractorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContractorsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContractors>>> = ({ signal }) => getContractors(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContractorsQueryResult = NonNullable<Awaited<ReturnType<typeof getContractors>>>
export type GetContractorsQueryError = unknown | ProblemDetails


export function useGetContractors<TData = Awaited<ReturnType<typeof getContractors>>, TError = unknown | ProblemDetails>(
 params: undefined |  GetContractorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContractors>>,
          TError,
          Awaited<ReturnType<typeof getContractors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContractors<TData = Awaited<ReturnType<typeof getContractors>>, TError = unknown | ProblemDetails>(
 params?: GetContractorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContractors>>,
          TError,
          Awaited<ReturnType<typeof getContractors>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContractors<TData = Awaited<ReturnType<typeof getContractors>>, TError = unknown | ProblemDetails>(
 params?: GetContractorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all contractors, optionally filtered by NIPs
 */

export function useGetContractors<TData = Awaited<ReturnType<typeof getContractors>>, TError = unknown | ProblemDetails>(
 params?: GetContractorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContractorsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createContractorResponse200 = {
  data: CreateContractorResponse
  status: 200
}

export type createContractorResponse404 = {
  data: unknown
  status: 404
}

export type createContractorResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type createContractorResponseSuccess = (createContractorResponse200) & {
  headers: Headers;
};
export type createContractorResponseError = (createContractorResponse404 | createContractorResponseDefault) & {
  headers: Headers;
};

export type createContractorResponse = (createContractorResponseSuccess | createContractorResponseError)

export const getCreateContractorUrl = () => {




  return `/contractors`
}

/**
 * POST_contractors
 * @summary Create a new contractor
 */
export const createContractor = async (createContractorCommand: CreateContractorCommand, options?: RequestInit): Promise<createContractorResponse> => {

  const res = await fetch(getCreateContractorUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createContractorCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createContractorResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createContractorResponse
}




export const getCreateContractorMutationOptions = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContractor>>, TError,{data: CreateContractorCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createContractor>>, TError,{data: CreateContractorCommand}, TContext> => {

const mutationKey = ['createContractor'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContractor>>, {data: CreateContractorCommand}> = (props) => {
          const {data} = props ?? {};

          return  createContractor(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateContractorMutationResult = NonNullable<Awaited<ReturnType<typeof createContractor>>>
    export type CreateContractorMutationBody = CreateContractorCommand
    export type CreateContractorMutationError = unknown | ProblemDetails

    /**
 * @summary Create a new contractor
 */
export const useCreateContractor = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContractor>>, TError,{data: CreateContractorCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createContractor>>,
        TError,
        {data: CreateContractorCommand},
        TContext
      > => {
      return useMutation(getCreateContractorMutationOptions(options), queryClient);
    }
