/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from ".././axios-instance";
import type {
	CreateContractorCommand,
	CreateContractorResponse,
	GetContractorResponse,
	GetContractorsParams,
	GetContractorsResponse,
	ProblemDetails,
	UpdateContractorCommand,
} from ".././models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * PUT_contractors_id
 * @summary Update contractor details
 */
export const updateContractor = (
	id: string,
	updateContractorCommand: UpdateContractorCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{
			url: `/contractors/${id}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: updateContractorCommand,
			signal,
		},
		options,
	);
};

export const getUpdateContractorMutationOptions = <
	TError = ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateContractor>>,
		TError,
		{ id: string; data: UpdateContractorCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateContractor>>,
	TError,
	{ id: string; data: UpdateContractorCommand },
	TContext
> => {
	const mutationKey = ["updateContractor"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateContractor>>,
		{ id: string; data: UpdateContractorCommand }
	> = (props) => {
		const { id, data } = props ?? {};

		return updateContractor(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateContractorMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateContractor>>
>;
export type UpdateContractorMutationBody = UpdateContractorCommand;
export type UpdateContractorMutationError = ProblemDetails;

/**
 * @summary Update contractor details
 */
export const useUpdateContractor = <
	TError = ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateContractor>>,
			TError,
			{ id: string; data: UpdateContractorCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateContractor>>,
	TError,
	{ id: string; data: UpdateContractorCommand },
	TContext
> => {
	return useMutation(getUpdateContractorMutationOptions(options), queryClient);
};
/**
 * GET_contractors_id
 * @summary Get contractor by ID
 */
export const getContractor = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetContractorResponse>(
		{ url: `/contractors/${id}`, method: "GET", signal },
		options,
	);
};

export const getGetContractorQueryKey = (id: string) => {
	return [`/contractors/${id}`] as const;
};

export const getGetContractorQueryOptions = <
	TData = Awaited<ReturnType<typeof getContractor>>,
	TError = unknown | ProblemDetails,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetContractorQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getContractor>>> = ({
		signal,
	}) => getContractor(id, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getContractor>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContractorQueryResult = NonNullable<
	Awaited<ReturnType<typeof getContractor>>
>;
export type GetContractorQueryError = unknown | ProblemDetails;

export function useGetContractor<
	TData = Awaited<ReturnType<typeof getContractor>>,
	TError = unknown | ProblemDetails,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContractor>>,
					TError,
					Awaited<ReturnType<typeof getContractor>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContractor<
	TData = Awaited<ReturnType<typeof getContractor>>,
	TError = unknown | ProblemDetails,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContractor>>,
					TError,
					Awaited<ReturnType<typeof getContractor>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContractor<
	TData = Awaited<ReturnType<typeof getContractor>>,
	TError = unknown | ProblemDetails,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get contractor by ID
 */

export function useGetContractor<
	TData = Awaited<ReturnType<typeof getContractor>>,
	TError = unknown | ProblemDetails,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractor>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetContractorQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * DELETE_contractors_id
 * @summary Delete contractor
 */
export const deleteContractor = (
	id: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{ url: `/contractors/${id}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteContractorMutationOptions = <
	TError = ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteContractor>>,
		TError,
		{ id: string },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteContractor>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteContractor"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteContractor>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteContractor(id, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteContractorMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteContractor>>
>;

export type DeleteContractorMutationError = ProblemDetails;

/**
 * @summary Delete contractor
 */
export const useDeleteContractor = <
	TError = ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteContractor>>,
			TError,
			{ id: string },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteContractor>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(getDeleteContractorMutationOptions(options), queryClient);
};
/**
 * GET_contractors
 * @summary Get all contractors, optionally filtered by NIPs
 */
export const getContractors = (
	params?: GetContractorsParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetContractorsResponse[]>(
		{ url: `/contractors`, method: "GET", params, signal },
		options,
	);
};

export const getGetContractorsQueryKey = (params?: GetContractorsParams) => {
	return [`/contractors`, ...(params ? [params] : [])] as const;
};

export const getGetContractorsQueryOptions = <
	TData = Awaited<ReturnType<typeof getContractors>>,
	TError = unknown | ProblemDetails,
>(
	params?: GetContractorsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetContractorsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getContractors>>> = ({
		signal,
	}) => getContractors(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getContractors>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContractorsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getContractors>>
>;
export type GetContractorsQueryError = unknown | ProblemDetails;

export function useGetContractors<
	TData = Awaited<ReturnType<typeof getContractors>>,
	TError = unknown | ProblemDetails,
>(
	params: undefined | GetContractorsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContractors>>,
					TError,
					Awaited<ReturnType<typeof getContractors>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContractors<
	TData = Awaited<ReturnType<typeof getContractors>>,
	TError = unknown | ProblemDetails,
>(
	params?: GetContractorsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getContractors>>,
					TError,
					Awaited<ReturnType<typeof getContractors>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContractors<
	TData = Awaited<ReturnType<typeof getContractors>>,
	TError = unknown | ProblemDetails,
>(
	params?: GetContractorsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all contractors, optionally filtered by NIPs
 */

export function useGetContractors<
	TData = Awaited<ReturnType<typeof getContractors>>,
	TError = unknown | ProblemDetails,
>(
	params?: GetContractorsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getContractors>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetContractorsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * POST_contractors
 * @summary Create a new contractor
 */
export const createContractor = (
	createContractorCommand: CreateContractorCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CreateContractorResponse>(
		{
			url: `/contractors`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createContractorCommand,
			signal,
		},
		options,
	);
};

export const getCreateContractorMutationOptions = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createContractor>>,
		TError,
		{ data: CreateContractorCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createContractor>>,
	TError,
	{ data: CreateContractorCommand },
	TContext
> => {
	const mutationKey = ["createContractor"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createContractor>>,
		{ data: CreateContractorCommand }
	> = (props) => {
		const { data } = props ?? {};

		return createContractor(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateContractorMutationResult = NonNullable<
	Awaited<ReturnType<typeof createContractor>>
>;
export type CreateContractorMutationBody = CreateContractorCommand;
export type CreateContractorMutationError = unknown | ProblemDetails;

/**
 * @summary Create a new contractor
 */
export const useCreateContractor = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createContractor>>,
			TError,
			{ data: CreateContractorCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createContractor>>,
	TError,
	{ data: CreateContractorCommand },
	TContext
> => {
	return useMutation(getCreateContractorMutationOptions(options), queryClient);
};
