/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppErrorsRouteImport } from './routes/_app/errors'
import { Route as AppContractorsIndexRouteImport } from './routes/_app/contractors/index'
import { Route as AppContractorsCreateRouteImport } from './routes/_app/contractors/create'
import { Route as AppContractorsContractorIdEditRouteImport } from './routes/_app/contractors/$contractorId/edit'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppErrorsRoute = AppErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AppRoute,
} as any)
const AppContractorsIndexRoute = AppContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => AppRoute,
} as any)
const AppContractorsCreateRoute = AppContractorsCreateRouteImport.update({
  id: '/contractors/create',
  path: '/contractors/create',
  getParentRoute: () => AppRoute,
} as any)
const AppContractorsContractorIdEditRoute =
  AppContractorsContractorIdEditRouteImport.update({
    id: '/contractors/$contractorId/edit',
    path: '/contractors/$contractorId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/errors': typeof AppErrorsRoute
  '/contractors/create': typeof AppContractorsCreateRoute
  '/contractors/': typeof AppContractorsIndexRoute
  '/contractors/$contractorId/edit': typeof AppContractorsContractorIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/errors': typeof AppErrorsRoute
  '/': typeof AppIndexRoute
  '/contractors/create': typeof AppContractorsCreateRoute
  '/contractors': typeof AppContractorsIndexRoute
  '/contractors/$contractorId/edit': typeof AppContractorsContractorIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/_app/errors': typeof AppErrorsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/contractors/create': typeof AppContractorsCreateRoute
  '/_app/contractors/': typeof AppContractorsIndexRoute
  '/_app/contractors/$contractorId/edit': typeof AppContractorsContractorIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/errors'
    | '/contractors/create'
    | '/contractors/'
    | '/contractors/$contractorId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/pending'
    | '/errors'
    | '/'
    | '/contractors/create'
    | '/contractors'
    | '/contractors/$contractorId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/pending'
    | '/_app/errors'
    | '/_app/'
    | '/_app/contractors/create'
    | '/_app/contractors/'
    | '/_app/contractors/$contractorId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors': {
      id: '/_app/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof AppErrorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contractors/': {
      id: '/_app/contractors/'
      path: '/contractors'
      fullPath: '/contractors/'
      preLoaderRoute: typeof AppContractorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contractors/create': {
      id: '/_app/contractors/create'
      path: '/contractors/create'
      fullPath: '/contractors/create'
      preLoaderRoute: typeof AppContractorsCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contractors/$contractorId/edit': {
      id: '/_app/contractors/$contractorId/edit'
      path: '/contractors/$contractorId/edit'
      fullPath: '/contractors/$contractorId/edit'
      preLoaderRoute: typeof AppContractorsContractorIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppErrorsRoute: typeof AppErrorsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppContractorsCreateRoute: typeof AppContractorsCreateRoute
  AppContractorsIndexRoute: typeof AppContractorsIndexRoute
  AppContractorsContractorIdEditRoute: typeof AppContractorsContractorIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppErrorsRoute: AppErrorsRoute,
  AppIndexRoute: AppIndexRoute,
  AppContractorsCreateRoute: AppContractorsCreateRoute,
  AppContractorsIndexRoute: AppContractorsIndexRoute,
  AppContractorsContractorIdEditRoute: AppContractorsContractorIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
