/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppErrorsRouteImport } from './routes/_app/errors'
import { Route as AppContractorsRouteImport } from './routes/_app/contractors'

const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppErrorsRoute = AppErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AppRoute,
} as any)
const AppContractorsRoute = AppContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/contractors': typeof AppContractorsRoute
  '/errors': typeof AppErrorsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/contractors': typeof AppContractorsRoute
  '/errors': typeof AppErrorsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/_app/contractors': typeof AppContractorsRoute
  '/_app/errors': typeof AppErrorsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/pending' | '/contractors' | '/errors'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/pending' | '/contractors' | '/errors' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/pending'
    | '/_app/contractors'
    | '/_app/errors'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors': {
      id: '/_app/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof AppErrorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contractors': {
      id: '/_app/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof AppContractorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContractorsRoute: typeof AppContractorsRoute
  AppErrorsRoute: typeof AppErrorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContractorsRoute: AppContractorsRoute,
  AppErrorsRoute: AppErrorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
