using Autodor.Modules.Contractors.Contracts.Models;
using Autodor.Modules.Contractors.Contracts.Queries;
using Autodor.Modules.Invoicing.Domain.Aggregates;
using Autodor.Modules.Invoicing.Domain.ValueObjects;
using Autodor.Modules.Invoicing.Infrastructure.Invoicing;
using Autodor.Modules.Invoicing.Infrastructure.Options;
using Autodot.Modules.Orders.Contracts.Models;
using Autodot.Modules.Orders.Contracts.Queries;
using BuildingBlocks.Infrastructure.Extensions;
using ErrorOr;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Wolverine;
using Wolverine.Http;

namespace Autodor.Modules.Invoicing.Features.CreateInvoices;

public class CreateInvoicesHandler
{
    [WolverinePost("/invoices/bulk")]
    [Tags("Invoicing")]
    [EndpointName("CreateInvoicesBulk")]
    [EndpointSummary("Create multiple invoices for date range")]
    public static async Task<IResult> Handle(
        CreateInvoicesCommand command,
        IMessageBus bus,
        IServiceProvider serviceProvider,
        IOptions<InvoicingOptions> options,
        ILogger<CreateInvoicesHandler> logger,
        CancellationToken ct)
    {
        logger.LogInformation("Creating bulk invoices for date range {DateFrom} to {DateTo}", command.DateFrom, command.DateTo);

        // Retrieve all orders within the specified date range (already filtered for exclusions by Orders module)
        var query = new GetOrdersByDateRangeQuery(command.DateFrom, command.DateTo);
        var orders = (await bus.InvokeAsync<IEnumerable<OrderDto>>(query, ct)).ToList();

        if (orders.Count == 0)
        {
            logger.LogWarning("No orders found for bulk invoice creation in date range {DateFrom} to {DateTo}", command.DateFrom, command.DateTo);
            return Error.NotFound("Orders.NotFound", "No orders found for bulk invoice creation").Problem();
        }

        logger.LogInformation("Found {OrderCount} orders for invoice creation", orders.Count);

        // Get unique contractor NIPs from orders for bulk contractor lookup
        var contractorNIPs = orders
            .Select(o => o.CustomerNumber) // Order customer number is the NIP
            .Where(nip => !string.IsNullOrWhiteSpace(nip))
            .Distinct()
            .ToList();

        var contractors = await bus.InvokeAsync<IEnumerable<ContractorDto>>(
            new GetContractorsByNIPsQuery(contractorNIPs), ct);

        var contractorDict = contractors.ToDictionary(c => c.NIP, c => c);

        // Group orders by contractor NIP for individual invoice creation
        var ordersByContractor = orders
            .Where(o => !string.IsNullOrWhiteSpace(o.CustomerNumber))
            .GroupBy(o => o.CustomerNumber) // Group by contractor number (which is NIP)
            .ToList();

        var invoiceService = serviceProvider.GetRequiredKeyedService<IInvoiceService>(options.Value.Provider);
        var invoicesCreated = 0;

        foreach (var contractorGroup in ordersByContractor)
        {
            var contractorNIP = contractorGroup.Key;

            if (!contractorDict.TryGetValue(contractorNIP, out var contractorDto))
            {
                logger.LogWarning("Contractor with NIP {NIP} not found, skipping", contractorNIP);
                continue;
            }

            // Map contractor DTO to domain value object
            var invoiceContractor = new Contractor(
                Name: contractorDto.Name,
                City: contractorDto.City,
                Street: contractorDto.Street,
                NIP: contractorDto.NIP,
                ZipCode: contractorDto.ZipCode,
                Email: contractorDto.Email
            );

            // Collect all items from this contractor's orders (already filtered for exclusions by Orders module)
            var invoiceItems = contractorGroup
                .SelectMany(order => order.Items)
                .Select(item => new InvoiceItem
                {
                    Name = item.Name,
                    Quantity = item.Quantity,
                    UnitPrice = Math.Round(item.Price, 2)
                })
                .ToList();

            var invoice = new Invoice
            {
                Number = null, // Auto-generated by invoice service
                IssueDate = DateTime.Today,
                SaleDate = command.DateTo, // Last date in the range
                PaymentDue = DateTime.Today.AddDays(14), // Standard 14-day payment terms
                Contractor = invoiceContractor,
                Items = invoiceItems.AsReadOnly()
            };

            await invoiceService.CreateInvoiceAsync(invoice, ct);
            invoicesCreated++;

            logger.LogInformation("Created invoice for contractor {NIP} ({Name}) with {ItemCount} items",
                contractorNIP, contractorDto.Name, invoiceItems.Count);
        }

        logger.LogInformation("Successfully created {InvoiceCount} invoices", invoicesCreated);

        return Results.Ok(new { InvoicesCreated = invoicesCreated });
    }
}
