/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from ".././axios-instance";
import type {
	ExcludeOrderCommand,
	ExcludeOrderItemCommand,
	GenerateDeliveryNoteCommand,
	GetOrderParams,
	GetOrdersParams,
	GetOrdersResponse,
	HttpValidationProblemDetails,
	IResult,
	ProblemDetails,
} from ".././models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * GET_orders_id
 * @summary Get order by ID and date
 */
export const getOrder = (
	id: string,
	params?: GetOrderParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<IResult>(
		{ url: `/orders/${id}`, method: "GET", params, signal },
		options,
	);
};

export const getGetOrderQueryKey = (id: string, params?: GetOrderParams) => {
	return [`/orders/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetOrderQueryOptions = <
	TData = Awaited<ReturnType<typeof getOrder>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	id: string,
	params?: GetOrderParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetOrderQueryKey(id, params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrder>>> = ({
		signal,
	}) => getOrder(id, params, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetOrderQueryResult = NonNullable<
	Awaited<ReturnType<typeof getOrder>>
>;
export type GetOrderQueryError =
	| HttpValidationProblemDetails
	| unknown
	| ProblemDetails;

export function useGetOrder<
	TData = Awaited<ReturnType<typeof getOrder>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	id: string,
	params: undefined | GetOrderParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOrder>>,
					TError,
					Awaited<ReturnType<typeof getOrder>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrder<
	TData = Awaited<ReturnType<typeof getOrder>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	id: string,
	params?: GetOrderParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOrder>>,
					TError,
					Awaited<ReturnType<typeof getOrder>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrder<
	TData = Awaited<ReturnType<typeof getOrder>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	id: string,
	params?: GetOrderParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get order by ID and date
 */

export function useGetOrder<
	TData = Awaited<ReturnType<typeof getOrder>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	id: string,
	params?: GetOrderParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetOrderQueryOptions(id, params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * PATCH_orders_id
 * @summary Include or exclude order from invoicing
 */
export const updateOrderExclusion = (
	id: string,
	excludeOrderCommand: ExcludeOrderCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<IResult>(
		{
			url: `/orders/${id}`,
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			data: excludeOrderCommand,
			signal,
		},
		options,
	);
};

export const getUpdateOrderExclusionMutationOptions = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateOrderExclusion>>,
		TError,
		{ id: string; data: ExcludeOrderCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateOrderExclusion>>,
	TError,
	{ id: string; data: ExcludeOrderCommand },
	TContext
> => {
	const mutationKey = ["updateOrderExclusion"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateOrderExclusion>>,
		{ id: string; data: ExcludeOrderCommand }
	> = (props) => {
		const { id, data } = props ?? {};

		return updateOrderExclusion(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateOrderExclusionMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateOrderExclusion>>
>;
export type UpdateOrderExclusionMutationBody = ExcludeOrderCommand;
export type UpdateOrderExclusionMutationError = unknown | ProblemDetails;

/**
 * @summary Include or exclude order from invoicing
 */
export const useUpdateOrderExclusion = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateOrderExclusion>>,
			TError,
			{ id: string; data: ExcludeOrderCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateOrderExclusion>>,
	TError,
	{ id: string; data: ExcludeOrderCommand },
	TContext
> => {
	return useMutation(
		getUpdateOrderExclusionMutationOptions(options),
		queryClient,
	);
};
/**
 * GET_orders
 * @summary Get all orders within date range
 */
export const getOrders = (
	params?: GetOrdersParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetOrdersResponse>(
		{ url: `/orders`, method: "GET", params, signal },
		options,
	);
};

export const getGetOrdersQueryKey = (params?: GetOrdersParams) => {
	return [`/orders`, ...(params ? [params] : [])] as const;
};

export const getGetOrdersQueryOptions = <
	TData = Awaited<ReturnType<typeof getOrders>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	params?: GetOrdersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetOrdersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrders>>> = ({
		signal,
	}) => getOrders(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getOrders>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrdersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getOrders>>
>;
export type GetOrdersQueryError =
	| HttpValidationProblemDetails
	| unknown
	| ProblemDetails;

export function useGetOrders<
	TData = Awaited<ReturnType<typeof getOrders>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	params: undefined | GetOrdersParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOrders>>,
					TError,
					Awaited<ReturnType<typeof getOrders>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrders<
	TData = Awaited<ReturnType<typeof getOrders>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	params?: GetOrdersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getOrders>>,
					TError,
					Awaited<ReturnType<typeof getOrders>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrders<
	TData = Awaited<ReturnType<typeof getOrders>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	params?: GetOrdersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all orders within date range
 */

export function useGetOrders<
	TData = Awaited<ReturnType<typeof getOrders>>,
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
>(
	params?: GetOrdersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetOrdersQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * POST_delivery_notes
 * @summary Generate PDF delivery note for an order
 */
export const generateDeliveryNote = (
	generateDeliveryNoteCommand: GenerateDeliveryNoteCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<IResult>(
		{
			url: `/delivery-notes`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: generateDeliveryNoteCommand,
			signal,
		},
		options,
	);
};

export const getGenerateDeliveryNoteMutationOptions = <
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof generateDeliveryNote>>,
		TError,
		{ data: GenerateDeliveryNoteCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof generateDeliveryNote>>,
	TError,
	{ data: GenerateDeliveryNoteCommand },
	TContext
> => {
	const mutationKey = ["generateDeliveryNote"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof generateDeliveryNote>>,
		{ data: GenerateDeliveryNoteCommand }
	> = (props) => {
		const { data } = props ?? {};

		return generateDeliveryNote(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type GenerateDeliveryNoteMutationResult = NonNullable<
	Awaited<ReturnType<typeof generateDeliveryNote>>
>;
export type GenerateDeliveryNoteMutationBody = GenerateDeliveryNoteCommand;
export type GenerateDeliveryNoteMutationError =
	| HttpValidationProblemDetails
	| unknown
	| ProblemDetails;

/**
 * @summary Generate PDF delivery note for an order
 */
export const useGenerateDeliveryNote = <
	TError = HttpValidationProblemDetails | unknown | ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof generateDeliveryNote>>,
			TError,
			{ data: GenerateDeliveryNoteCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof generateDeliveryNote>>,
	TError,
	{ data: GenerateDeliveryNoteCommand },
	TContext
> => {
	return useMutation(
		getGenerateDeliveryNoteMutationOptions(options),
		queryClient,
	);
};
/**
 * PATCH_orders_id_items_itemNumber
 * @summary Include or exclude order item from invoicing
 */
export const updateOrderItemExclusion = (
	id: string,
	itemNumber: string,
	excludeOrderItemCommand: ExcludeOrderItemCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<IResult>(
		{
			url: `/orders/${id}/items/${itemNumber}`,
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			data: excludeOrderItemCommand,
			signal,
		},
		options,
	);
};

export const getUpdateOrderItemExclusionMutationOptions = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateOrderItemExclusion>>,
		TError,
		{ id: string; itemNumber: string; data: ExcludeOrderItemCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateOrderItemExclusion>>,
	TError,
	{ id: string; itemNumber: string; data: ExcludeOrderItemCommand },
	TContext
> => {
	const mutationKey = ["updateOrderItemExclusion"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateOrderItemExclusion>>,
		{ id: string; itemNumber: string; data: ExcludeOrderItemCommand }
	> = (props) => {
		const { id, itemNumber, data } = props ?? {};

		return updateOrderItemExclusion(id, itemNumber, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateOrderItemExclusionMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateOrderItemExclusion>>
>;
export type UpdateOrderItemExclusionMutationBody = ExcludeOrderItemCommand;
export type UpdateOrderItemExclusionMutationError = unknown | ProblemDetails;

/**
 * @summary Include or exclude order item from invoicing
 */
export const useUpdateOrderItemExclusion = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateOrderItemExclusion>>,
			TError,
			{ id: string; itemNumber: string; data: ExcludeOrderItemCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateOrderItemExclusion>>,
	TError,
	{ id: string; itemNumber: string; data: ExcludeOrderItemCommand },
	TContext
> => {
	return useMutation(
		getUpdateOrderItemExclusionMutationOptions(options),
		queryClient,
	);
};
