/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExcludeOrderCommand,
  ExcludeOrderItemCommand,
  GenerateDeliveryNoteCommand,
  GetOrderParams,
  GetOrdersParams,
  GetOrdersResponse,
  HttpValidationProblemDetails,
  IResult,
  ProblemDetails
} from '../models';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type getOrderResponse200 = {
  data: IResult
  status: 200
}

export type getOrderResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getOrderResponse404 = {
  data: unknown
  status: 404
}

export type getOrderResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type getOrderResponseSuccess = (getOrderResponse200) & {
  headers: Headers;
};
export type getOrderResponseError = (getOrderResponse400 | getOrderResponse404 | getOrderResponseDefault) & {
  headers: Headers;
};

export type getOrderResponse = (getOrderResponseSuccess | getOrderResponseError)

export const getGetOrderUrl = (id: string,
    params?: GetOrderParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/orders/${id}?${stringifiedParams}` : `/api/orders/${id}`
}

/**
 * GET_api_orders_id
 * @summary Get order by ID and date
 */
export const getOrder = async (id: string,
    params?: GetOrderParams, options?: RequestInit): Promise<getOrderResponse> => {

  const res = await fetch(getGetOrderUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrderResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOrderResponse
}





export const getGetOrderQueryKey = (id: string,
    params?: GetOrderParams,) => {
    return [
    `/api/orders/${id}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOrderQueryOptions = <TData = Awaited<ReturnType<typeof getOrder>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(id: string,
    params?: GetOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrderQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrder>>> = ({ signal }) => getOrder(id,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getOrder>>>
export type GetOrderQueryError = HttpValidationProblemDetails | unknown | ProblemDetails


export function useGetOrder<TData = Awaited<ReturnType<typeof getOrder>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 id: string,
    params: undefined |  GetOrderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrder>>,
          TError,
          Awaited<ReturnType<typeof getOrder>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrder<TData = Awaited<ReturnType<typeof getOrder>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 id: string,
    params?: GetOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrder>>,
          TError,
          Awaited<ReturnType<typeof getOrder>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrder<TData = Awaited<ReturnType<typeof getOrder>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 id: string,
    params?: GetOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get order by ID and date
 */

export function useGetOrder<TData = Awaited<ReturnType<typeof getOrder>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 id: string,
    params?: GetOrderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrderQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateOrderExclusionResponse200 = {
  data: IResult
  status: 200
}

export type updateOrderExclusionResponse404 = {
  data: unknown
  status: 404
}

export type updateOrderExclusionResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type updateOrderExclusionResponseSuccess = (updateOrderExclusionResponse200) & {
  headers: Headers;
};
export type updateOrderExclusionResponseError = (updateOrderExclusionResponse404 | updateOrderExclusionResponseDefault) & {
  headers: Headers;
};

export type updateOrderExclusionResponse = (updateOrderExclusionResponseSuccess | updateOrderExclusionResponseError)

export const getUpdateOrderExclusionUrl = (id: string,) => {




  return `/api/orders/${id}`
}

/**
 * PATCH_api_orders_id
 * @summary Include or exclude order from invoicing
 */
export const updateOrderExclusion = async (id: string,
    excludeOrderCommand: ExcludeOrderCommand, options?: RequestInit): Promise<updateOrderExclusionResponse> => {

  const res = await fetch(getUpdateOrderExclusionUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      excludeOrderCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateOrderExclusionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateOrderExclusionResponse
}




export const getUpdateOrderExclusionMutationOptions = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderExclusion>>, TError,{id: string;data: ExcludeOrderCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrderExclusion>>, TError,{id: string;data: ExcludeOrderCommand}, TContext> => {

const mutationKey = ['updateOrderExclusion'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrderExclusion>>, {id: string;data: ExcludeOrderCommand}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOrderExclusion(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderExclusionMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrderExclusion>>>
    export type UpdateOrderExclusionMutationBody = ExcludeOrderCommand
    export type UpdateOrderExclusionMutationError = unknown | ProblemDetails

    /**
 * @summary Include or exclude order from invoicing
 */
export const useUpdateOrderExclusion = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderExclusion>>, TError,{id: string;data: ExcludeOrderCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrderExclusion>>,
        TError,
        {id: string;data: ExcludeOrderCommand},
        TContext
      > => {
      return useMutation(getUpdateOrderExclusionMutationOptions(options), queryClient);
    }
    export type getOrdersResponse200 = {
  data: GetOrdersResponse
  status: 200
}

export type getOrdersResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getOrdersResponse404 = {
  data: unknown
  status: 404
}

export type getOrdersResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type getOrdersResponseSuccess = (getOrdersResponse200) & {
  headers: Headers;
};
export type getOrdersResponseError = (getOrdersResponse400 | getOrdersResponse404 | getOrdersResponseDefault) & {
  headers: Headers;
};

export type getOrdersResponse = (getOrdersResponseSuccess | getOrdersResponseError)

export const getGetOrdersUrl = (params?: GetOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/orders?${stringifiedParams}` : `/api/orders`
}

/**
 * GET_api_orders
 * @summary Get all orders within date range
 */
export const getOrders = async (params?: GetOrdersParams, options?: RequestInit): Promise<getOrdersResponse> => {

  const res = await fetch(getGetOrdersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getOrdersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOrdersResponse
}





export const getGetOrdersQueryKey = (params?: GetOrdersParams,) => {
    return [
    `/api/orders`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getOrders>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrders>>> = ({ signal }) => getOrders(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getOrders>>>
export type GetOrdersQueryError = HttpValidationProblemDetails | unknown | ProblemDetails


export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 params: undefined |  GetOrdersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrders>>,
          TError,
          Awaited<ReturnType<typeof getOrders>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrders>>,
          TError,
          Awaited<ReturnType<typeof getOrders>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all orders within date range
 */

export function useGetOrders<TData = Awaited<ReturnType<typeof getOrders>>, TError = HttpValidationProblemDetails | unknown | ProblemDetails>(
 params?: GetOrdersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type generateDeliveryNoteResponse200 = {
  data: IResult
  status: 200
}

export type generateDeliveryNoteResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type generateDeliveryNoteResponse404 = {
  data: unknown
  status: 404
}

export type generateDeliveryNoteResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 400 | 404>
}

export type generateDeliveryNoteResponseSuccess = (generateDeliveryNoteResponse200) & {
  headers: Headers;
};
export type generateDeliveryNoteResponseError = (generateDeliveryNoteResponse400 | generateDeliveryNoteResponse404 | generateDeliveryNoteResponseDefault) & {
  headers: Headers;
};

export type generateDeliveryNoteResponse = (generateDeliveryNoteResponseSuccess | generateDeliveryNoteResponseError)

export const getGenerateDeliveryNoteUrl = () => {




  return `/api/delivery-notes`
}

/**
 * POST_api_delivery_notes
 * @summary Generate PDF delivery note for an order
 */
export const generateDeliveryNote = async (generateDeliveryNoteCommand: GenerateDeliveryNoteCommand, options?: RequestInit): Promise<generateDeliveryNoteResponse> => {

  const res = await fetch(getGenerateDeliveryNoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      generateDeliveryNoteCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: generateDeliveryNoteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as generateDeliveryNoteResponse
}




export const getGenerateDeliveryNoteMutationOptions = <TError = HttpValidationProblemDetails | unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateDeliveryNote>>, TError,{data: GenerateDeliveryNoteCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof generateDeliveryNote>>, TError,{data: GenerateDeliveryNoteCommand}, TContext> => {

const mutationKey = ['generateDeliveryNote'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateDeliveryNote>>, {data: GenerateDeliveryNoteCommand}> = (props) => {
          const {data} = props ?? {};

          return  generateDeliveryNote(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GenerateDeliveryNoteMutationResult = NonNullable<Awaited<ReturnType<typeof generateDeliveryNote>>>
    export type GenerateDeliveryNoteMutationBody = GenerateDeliveryNoteCommand
    export type GenerateDeliveryNoteMutationError = HttpValidationProblemDetails | unknown | ProblemDetails

    /**
 * @summary Generate PDF delivery note for an order
 */
export const useGenerateDeliveryNote = <TError = HttpValidationProblemDetails | unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateDeliveryNote>>, TError,{data: GenerateDeliveryNoteCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateDeliveryNote>>,
        TError,
        {data: GenerateDeliveryNoteCommand},
        TContext
      > => {
      return useMutation(getGenerateDeliveryNoteMutationOptions(options), queryClient);
    }
    export type updateOrderItemExclusionResponse200 = {
  data: IResult
  status: 200
}

export type updateOrderItemExclusionResponse404 = {
  data: unknown
  status: 404
}

export type updateOrderItemExclusionResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type updateOrderItemExclusionResponseSuccess = (updateOrderItemExclusionResponse200) & {
  headers: Headers;
};
export type updateOrderItemExclusionResponseError = (updateOrderItemExclusionResponse404 | updateOrderItemExclusionResponseDefault) & {
  headers: Headers;
};

export type updateOrderItemExclusionResponse = (updateOrderItemExclusionResponseSuccess | updateOrderItemExclusionResponseError)

export const getUpdateOrderItemExclusionUrl = (id: string,
    itemNumber: string,) => {




  return `/api/orders/${id}/items/${itemNumber}`
}

/**
 * PATCH_api_orders_id_items_itemNumber
 * @summary Include or exclude order item from invoicing
 */
export const updateOrderItemExclusion = async (id: string,
    itemNumber: string,
    excludeOrderItemCommand: ExcludeOrderItemCommand, options?: RequestInit): Promise<updateOrderItemExclusionResponse> => {

  const res = await fetch(getUpdateOrderItemExclusionUrl(id,itemNumber),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      excludeOrderItemCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateOrderItemExclusionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateOrderItemExclusionResponse
}




export const getUpdateOrderItemExclusionMutationOptions = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderItemExclusion>>, TError,{id: string;itemNumber: string;data: ExcludeOrderItemCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrderItemExclusion>>, TError,{id: string;itemNumber: string;data: ExcludeOrderItemCommand}, TContext> => {

const mutationKey = ['updateOrderItemExclusion'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrderItemExclusion>>, {id: string;itemNumber: string;data: ExcludeOrderItemCommand}> = (props) => {
          const {id,itemNumber,data} = props ?? {};

          return  updateOrderItemExclusion(id,itemNumber,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrderItemExclusionMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrderItemExclusion>>>
    export type UpdateOrderItemExclusionMutationBody = ExcludeOrderItemCommand
    export type UpdateOrderItemExclusionMutationError = unknown | ProblemDetails

    /**
 * @summary Include or exclude order item from invoicing
 */
export const useUpdateOrderItemExclusion = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrderItemExclusion>>, TError,{id: string;itemNumber: string;data: ExcludeOrderItemCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrderItemExclusion>>,
        TError,
        {id: string;itemNumber: string;data: ExcludeOrderItemCommand},
        TContext
      > => {
      return useMutation(getUpdateOrderItemExclusionMutationOptions(options), queryClient);
    }
