/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * GET_orders_id
 * @summary Get order by ID and date
 */
export const GetOrderParams = zod.object({
	id: zod.string(),
});

export const GetOrderQueryParams = zod.object({
	date: zod.iso.datetime({}).optional(),
});

export const GetOrderResponse = zod.looseObject({});

/**
 * PATCH_orders_id
 * @summary Include or exclude order from invoicing
 */
export const UpdateOrderExclusionParams = zod.object({
	id: zod.string(),
});

export const UpdateOrderExclusionBody = zod.object({
	excluded: zod.boolean().optional(),
});

export const UpdateOrderExclusionResponse = zod.looseObject({});

/**
 * GET_orders
 * @summary Get all orders within date range
 */
export const GetOrdersQueryParams = zod.object({
	from: zod.iso.datetime({}).optional(),
	to: zod.iso.datetime({}).optional(),
});

export const GetOrdersResponse = zod.object({
	orders: zod.array(
		zod.object({
			id: zod.string(),
			number: zod.string().nullable(),
			date: zod.iso.datetime({}),
			person: zod.string().nullable(),
			customerNumber: zod.string().nullable(),
			itemsCount: zod.number(),
			totalAmount: zod.number(),
			isExcluded: zod.boolean(),
			excludedItemsCount: zod.number(),
		}),
	),
});

/**
 * POST_delivery_notes
 * @summary Generate PDF delivery note for an order
 */
export const GenerateDeliveryNoteBody = zod.object({
	orderId: zod.string().optional(),
	date: zod.iso.datetime({}).optional(),
});

export const GenerateDeliveryNoteResponse = zod.looseObject({});

/**
 * PATCH_orders_id_items_itemNumber
 * @summary Include or exclude order item from invoicing
 */
export const UpdateOrderItemExclusionParams = zod.object({
	id: zod.string(),
	itemNumber: zod.string(),
});

export const UpdateOrderItemExclusionBody = zod.object({
	excluded: zod.boolean().optional(),
});

export const UpdateOrderItemExclusionResponse = zod.looseObject({});
