/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Validate an AsParameters query model with FluentValidation and return problem details on failure
 */
export const createValidationModelErrorQueryQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const CreateValidationModelErrorQueryParams = zod.object({
  "Name": zod.string().optional(),
  "Email": zod.string().optional(),
  "Quantity": zod.union([zod.number(),zod.stringFormat('int32', createValidationModelErrorQueryQuantityRegExpTwo)])
})

