/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateValidationModelErrorParams,
  HttpValidationProblemDetails
} from '../models';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getCreateValidationModelErrorUrl = (params?: CreateValidationModelErrorParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/errors/validation-model?${stringifiedParams}` : `/api/errors/validation-model`
}

/**
 * GET_api_errors_validation_model
 * @summary Validate an AsParameters query model with FluentValidation and return problem details on failure
 */
export const createValidationModelError = async (params?: CreateValidationModelErrorParams, options?: RequestInit): Promise<string> => {

  return customFetch<string>(getCreateValidationModelErrorUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getCreateValidationModelErrorQueryKey = (params?: CreateValidationModelErrorParams,) => {
    return [
    `/api/errors/validation-model`, ...(params ? [params] : [])
    ] as const;
    }


export const getCreateValidationModelErrorQueryOptions = <TData = Awaited<ReturnType<typeof createValidationModelError>>, TError = HttpValidationProblemDetails>(params?: CreateValidationModelErrorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createValidationModelError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateValidationModelErrorQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createValidationModelError>>> = ({ signal }) => createValidationModelError(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createValidationModelError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateValidationModelErrorQueryResult = NonNullable<Awaited<ReturnType<typeof createValidationModelError>>>
export type CreateValidationModelErrorQueryError = HttpValidationProblemDetails


export function useCreateValidationModelError<TData = Awaited<ReturnType<typeof createValidationModelError>>, TError = HttpValidationProblemDetails>(
 params: undefined |  CreateValidationModelErrorParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createValidationModelError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createValidationModelError>>,
          TError,
          Awaited<ReturnType<typeof createValidationModelError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateValidationModelError<TData = Awaited<ReturnType<typeof createValidationModelError>>, TError = HttpValidationProblemDetails>(
 params?: CreateValidationModelErrorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createValidationModelError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createValidationModelError>>,
          TError,
          Awaited<ReturnType<typeof createValidationModelError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateValidationModelError<TData = Awaited<ReturnType<typeof createValidationModelError>>, TError = HttpValidationProblemDetails>(
 params?: CreateValidationModelErrorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createValidationModelError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Validate an AsParameters query model with FluentValidation and return problem details on failure
 */

export function useCreateValidationModelError<TData = Awaited<ReturnType<typeof createValidationModelError>>, TError = HttpValidationProblemDetails>(
 params?: CreateValidationModelErrorParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createValidationModelError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateValidationModelErrorQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetUnauthorizedErrorUrl = () => {




  return `/api/errors/unauthorized`
}

/**
 * GET_api_errors_unauthorized
 * @summary Return a 401 problem details response
 */
export const getUnauthorizedError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetUnauthorizedErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUnauthorizedErrorQueryKey = () => {
    return [
    `/api/errors/unauthorized`
    ] as const;
    }


export const getGetUnauthorizedErrorQueryOptions = <TData = Awaited<ReturnType<typeof getUnauthorizedError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnauthorizedError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnauthorizedErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnauthorizedError>>> = ({ signal }) => getUnauthorizedError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnauthorizedError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUnauthorizedErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getUnauthorizedError>>>
export type GetUnauthorizedErrorQueryError = HttpValidationProblemDetails


export function useGetUnauthorizedError<TData = Awaited<ReturnType<typeof getUnauthorizedError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnauthorizedError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnauthorizedError>>,
          TError,
          Awaited<ReturnType<typeof getUnauthorizedError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnauthorizedError<TData = Awaited<ReturnType<typeof getUnauthorizedError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnauthorizedError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnauthorizedError>>,
          TError,
          Awaited<ReturnType<typeof getUnauthorizedError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnauthorizedError<TData = Awaited<ReturnType<typeof getUnauthorizedError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnauthorizedError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return a 401 problem details response
 */

export function useGetUnauthorizedError<TData = Awaited<ReturnType<typeof getUnauthorizedError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnauthorizedError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUnauthorizedErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetSecuredErrorUrl = () => {




  return `/api/errors/secured`
}

/**
 * GET_api_errors_secured
 * @summary Require a fake role-derived permission to demonstrate authorization errors
 */
export const getSecuredError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetSecuredErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSecuredErrorQueryKey = () => {
    return [
    `/api/errors/secured`
    ] as const;
    }


export const getGetSecuredErrorQueryOptions = <TData = Awaited<ReturnType<typeof getSecuredError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecuredError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSecuredErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSecuredError>>> = ({ signal }) => getSecuredError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSecuredError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSecuredErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getSecuredError>>>
export type GetSecuredErrorQueryError = HttpValidationProblemDetails


export function useGetSecuredError<TData = Awaited<ReturnType<typeof getSecuredError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecuredError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecuredError>>,
          TError,
          Awaited<ReturnType<typeof getSecuredError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSecuredError<TData = Awaited<ReturnType<typeof getSecuredError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecuredError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecuredError>>,
          TError,
          Awaited<ReturnType<typeof getSecuredError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSecuredError<TData = Awaited<ReturnType<typeof getSecuredError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecuredError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Require a fake role-derived permission to demonstrate authorization errors
 */

export function useGetSecuredError<TData = Awaited<ReturnType<typeof getSecuredError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecuredError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSecuredErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetNotFoundErrorUrl = () => {




  return `/api/errors/not-found`
}

/**
 * GET_api_errors_not_found
 * @summary Return a 404 problem details response
 */
export const getNotFoundError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetNotFoundErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetNotFoundErrorQueryKey = () => {
    return [
    `/api/errors/not-found`
    ] as const;
    }


export const getGetNotFoundErrorQueryOptions = <TData = Awaited<ReturnType<typeof getNotFoundError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotFoundError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotFoundErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotFoundError>>> = ({ signal }) => getNotFoundError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotFoundError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotFoundErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getNotFoundError>>>
export type GetNotFoundErrorQueryError = HttpValidationProblemDetails


export function useGetNotFoundError<TData = Awaited<ReturnType<typeof getNotFoundError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotFoundError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotFoundError>>,
          TError,
          Awaited<ReturnType<typeof getNotFoundError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotFoundError<TData = Awaited<ReturnType<typeof getNotFoundError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotFoundError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotFoundError>>,
          TError,
          Awaited<ReturnType<typeof getNotFoundError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotFoundError<TData = Awaited<ReturnType<typeof getNotFoundError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotFoundError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return a 404 problem details response
 */

export function useGetNotFoundError<TData = Awaited<ReturnType<typeof getNotFoundError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotFoundError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotFoundErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetInternalServerErrorUrl = () => {




  return `/api/errors/internal-server-error`
}

/**
 * GET_api_errors_internal_server_error
 * @summary Return a 500 problem details response
 */
export const getInternalServerError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetInternalServerErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInternalServerErrorQueryKey = () => {
    return [
    `/api/errors/internal-server-error`
    ] as const;
    }


export const getGetInternalServerErrorQueryOptions = <TData = Awaited<ReturnType<typeof getInternalServerError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInternalServerError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInternalServerErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInternalServerError>>> = ({ signal }) => getInternalServerError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInternalServerError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInternalServerErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getInternalServerError>>>
export type GetInternalServerErrorQueryError = HttpValidationProblemDetails


export function useGetInternalServerError<TData = Awaited<ReturnType<typeof getInternalServerError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInternalServerError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInternalServerError>>,
          TError,
          Awaited<ReturnType<typeof getInternalServerError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInternalServerError<TData = Awaited<ReturnType<typeof getInternalServerError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInternalServerError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInternalServerError>>,
          TError,
          Awaited<ReturnType<typeof getInternalServerError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInternalServerError<TData = Awaited<ReturnType<typeof getInternalServerError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInternalServerError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return a 500 problem details response
 */

export function useGetInternalServerError<TData = Awaited<ReturnType<typeof getInternalServerError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInternalServerError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInternalServerErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetForbiddenErrorUrl = () => {




  return `/api/errors/forbidden`
}

/**
 * GET_api_errors_forbidden
 * @summary Return a 403 problem details response
 */
export const getForbiddenError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetForbiddenErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetForbiddenErrorQueryKey = () => {
    return [
    `/api/errors/forbidden`
    ] as const;
    }


export const getGetForbiddenErrorQueryOptions = <TData = Awaited<ReturnType<typeof getForbiddenError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getForbiddenError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetForbiddenErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getForbiddenError>>> = ({ signal }) => getForbiddenError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getForbiddenError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetForbiddenErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getForbiddenError>>>
export type GetForbiddenErrorQueryError = HttpValidationProblemDetails


export function useGetForbiddenError<TData = Awaited<ReturnType<typeof getForbiddenError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getForbiddenError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getForbiddenError>>,
          TError,
          Awaited<ReturnType<typeof getForbiddenError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetForbiddenError<TData = Awaited<ReturnType<typeof getForbiddenError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getForbiddenError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getForbiddenError>>,
          TError,
          Awaited<ReturnType<typeof getForbiddenError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetForbiddenError<TData = Awaited<ReturnType<typeof getForbiddenError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getForbiddenError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return a 403 problem details response
 */

export function useGetForbiddenError<TData = Awaited<ReturnType<typeof getForbiddenError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getForbiddenError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetForbiddenErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetDomainExceptionErrorUrl = () => {




  return `/api/errors/domain-exception`
}

/**
 * GET_api_errors_domain_exception
 * @summary Return a 400 domain rule violation problem details response
 */
export const getDomainExceptionError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetDomainExceptionErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDomainExceptionErrorQueryKey = () => {
    return [
    `/api/errors/domain-exception`
    ] as const;
    }


export const getGetDomainExceptionErrorQueryOptions = <TData = Awaited<ReturnType<typeof getDomainExceptionError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomainExceptionError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDomainExceptionErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDomainExceptionError>>> = ({ signal }) => getDomainExceptionError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDomainExceptionError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDomainExceptionErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getDomainExceptionError>>>
export type GetDomainExceptionErrorQueryError = HttpValidationProblemDetails


export function useGetDomainExceptionError<TData = Awaited<ReturnType<typeof getDomainExceptionError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomainExceptionError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDomainExceptionError>>,
          TError,
          Awaited<ReturnType<typeof getDomainExceptionError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDomainExceptionError<TData = Awaited<ReturnType<typeof getDomainExceptionError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomainExceptionError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDomainExceptionError>>,
          TError,
          Awaited<ReturnType<typeof getDomainExceptionError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDomainExceptionError<TData = Awaited<ReturnType<typeof getDomainExceptionError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomainExceptionError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return a 400 domain rule violation problem details response
 */

export function useGetDomainExceptionError<TData = Awaited<ReturnType<typeof getDomainExceptionError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomainExceptionError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDomainExceptionErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetBadRequestErrorUrl = () => {




  return `/api/errors/bad-request`
}

/**
 * GET_api_errors_bad_request
 * @summary Return a 400 validation problem details response
 */
export const getBadRequestError = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getGetBadRequestErrorUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetBadRequestErrorQueryKey = () => {
    return [
    `/api/errors/bad-request`
    ] as const;
    }


export const getGetBadRequestErrorQueryOptions = <TData = Awaited<ReturnType<typeof getBadRequestError>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBadRequestError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBadRequestErrorQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBadRequestError>>> = ({ signal }) => getBadRequestError({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBadRequestError>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBadRequestErrorQueryResult = NonNullable<Awaited<ReturnType<typeof getBadRequestError>>>
export type GetBadRequestErrorQueryError = HttpValidationProblemDetails


export function useGetBadRequestError<TData = Awaited<ReturnType<typeof getBadRequestError>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBadRequestError>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBadRequestError>>,
          TError,
          Awaited<ReturnType<typeof getBadRequestError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBadRequestError<TData = Awaited<ReturnType<typeof getBadRequestError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBadRequestError>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBadRequestError>>,
          TError,
          Awaited<ReturnType<typeof getBadRequestError>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBadRequestError<TData = Awaited<ReturnType<typeof getBadRequestError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBadRequestError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Return a 400 validation problem details response
 */

export function useGetBadRequestError<TData = Awaited<ReturnType<typeof getBadRequestError>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBadRequestError>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBadRequestErrorQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






