/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateInvoiceCommand {
	/** @nullable */
	invoiceNumber: number | null;
	saleDate: string;
	issueDate: string;
	dates: string[];
	orderIds: string[];
	contractorNip: string;
}
