/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OrderSummaryResponse } from "./orderSummaryResponse";

export interface GetOrdersResponse {
	orders: OrderSummaryResponse[];
}
