/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HttpValidationProblemDetailsErrors } from "./httpValidationProblemDetailsErrors";

export interface HttpValidationProblemDetails {
	/** @nullable */
	type?: string | null;
	/** @nullable */
	title?: string | null;
	/** @nullable */
	status?: number | null;
	/** @nullable */
	detail?: string | null;
	/** @nullable */
	instance?: string | null;
	errors?: HttpValidationProblemDetailsErrors;
}
