/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OrderItemResponse {
  productDisplayName: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  quantity: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  price: number | string;
  isExcluded: boolean;
}
