/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OrderSummaryResponse {
	id: string;
	/** @nullable */
	number: string | null;
	date: string;
	/** @nullable */
	person: string | null;
	/** @nullable */
	customerNumber: string | null;
	itemsCount: number;
	totalAmount: number;
	isExcluded: boolean;
	excludedItemsCount: number;
}
