/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProblemDetailsErrors } from './problemDetailsErrors';

/**
 * RFC 7807 Problem Details for HTTP APIs
 */
export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  status?: number | string | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** The trace identifier for request tracking. */
  traceId?: string;
  /** Timestamp when the error occurred (UTC). */
  timestamp?: string;
  /** Validation errors grouped by field name. */
  errors?: ProblemDetailsErrors;
}
