/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Validation errors grouped by field name.
 */
export type ProblemDetailsErrors = {[key: string]: string[]};
