/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateContractorCommand {
	nip: string;
	name: string;
	street: string;
	city: string;
	zipCode: string;
	email: string;
}
