/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * POST_invoices
 * @summary Create a single invoice for selected orders
 */
export const CreateInvoiceBody = zod.object({
	invoiceNumber: zod.number().nullable(),
	saleDate: zod.iso.datetime({}),
	issueDate: zod.iso.datetime({}),
	dates: zod.array(zod.iso.datetime({})),
	orderIds: zod.array(zod.string()),
	contractorNip: zod.string(),
});

export const CreateInvoiceResponse = zod.looseObject({});

/**
 * POST_invoices_bulk
 * @summary Create multiple invoices for date range
 */
export const CreateInvoicesBulkBody = zod.object({
	dateFrom: zod.iso.datetime({}),
	dateTo: zod.iso.datetime({}),
});

export const CreateInvoicesBulkResponse = zod.looseObject({});
