/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { customInstance } from ".././axios-instance";
import type {
	CreateInvoiceCommand,
	CreateInvoicesCommand,
	IResult,
	ProblemDetails,
} from ".././models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * POST_invoices
 * @summary Create a single invoice for selected orders
 */
export const createInvoice = (
	createInvoiceCommand: CreateInvoiceCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<IResult>(
		{
			url: `/invoices`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createInvoiceCommand,
			signal,
		},
		options,
	);
};

export const getCreateInvoiceMutationOptions = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createInvoice>>,
		TError,
		{ data: CreateInvoiceCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createInvoice>>,
	TError,
	{ data: CreateInvoiceCommand },
	TContext
> => {
	const mutationKey = ["createInvoice"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createInvoice>>,
		{ data: CreateInvoiceCommand }
	> = (props) => {
		const { data } = props ?? {};

		return createInvoice(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateInvoiceMutationResult = NonNullable<
	Awaited<ReturnType<typeof createInvoice>>
>;
export type CreateInvoiceMutationBody = CreateInvoiceCommand;
export type CreateInvoiceMutationError = unknown | ProblemDetails;

/**
 * @summary Create a single invoice for selected orders
 */
export const useCreateInvoice = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createInvoice>>,
			TError,
			{ data: CreateInvoiceCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createInvoice>>,
	TError,
	{ data: CreateInvoiceCommand },
	TContext
> => {
	return useMutation(getCreateInvoiceMutationOptions(options), queryClient);
};
/**
 * POST_invoices_bulk
 * @summary Create multiple invoices for date range
 */
export const createInvoicesBulk = (
	createInvoicesCommand: CreateInvoicesCommand,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<IResult>(
		{
			url: `/invoices/bulk`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createInvoicesCommand,
			signal,
		},
		options,
	);
};

export const getCreateInvoicesBulkMutationOptions = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createInvoicesBulk>>,
		TError,
		{ data: CreateInvoicesCommand },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createInvoicesBulk>>,
	TError,
	{ data: CreateInvoicesCommand },
	TContext
> => {
	const mutationKey = ["createInvoicesBulk"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createInvoicesBulk>>,
		{ data: CreateInvoicesCommand }
	> = (props) => {
		const { data } = props ?? {};

		return createInvoicesBulk(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateInvoicesBulkMutationResult = NonNullable<
	Awaited<ReturnType<typeof createInvoicesBulk>>
>;
export type CreateInvoicesBulkMutationBody = CreateInvoicesCommand;
export type CreateInvoicesBulkMutationError = unknown | ProblemDetails;

/**
 * @summary Create multiple invoices for date range
 */
export const useCreateInvoicesBulk = <
	TError = unknown | ProblemDetails,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createInvoicesBulk>>,
			TError,
			{ data: CreateInvoicesCommand },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createInvoicesBulk>>,
	TError,
	{ data: CreateInvoicesCommand },
	TContext
> => {
	return useMutation(
		getCreateInvoicesBulkMutationOptions(options),
		queryClient,
	);
};
