/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateInvoiceCommand,
  CreateInvoicesCommand,
  IResult,
  ProblemDetails
} from '../models';





export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;


export type createInvoiceResponse200 = {
  data: IResult
  status: 200
}

export type createInvoiceResponse404 = {
  data: unknown
  status: 404
}

export type createInvoiceResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type createInvoiceResponseSuccess = (createInvoiceResponse200) & {
  headers: Headers;
};
export type createInvoiceResponseError = (createInvoiceResponse404 | createInvoiceResponseDefault) & {
  headers: Headers;
};

export type createInvoiceResponse = (createInvoiceResponseSuccess | createInvoiceResponseError)

export const getCreateInvoiceUrl = () => {




  return `/api/invoices`
}

/**
 * POST_api_invoices
 * @summary Create a single invoice for selected orders
 */
export const createInvoice = async (createInvoiceCommand: CreateInvoiceCommand, options?: RequestInit): Promise<createInvoiceResponse> => {

  const res = await fetch(getCreateInvoiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInvoiceCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createInvoiceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createInvoiceResponse
}




export const getCreateInvoiceMutationOptions = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvoice>>, TError,{data: CreateInvoiceCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createInvoice>>, TError,{data: CreateInvoiceCommand}, TContext> => {

const mutationKey = ['createInvoice'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvoice>>, {data: CreateInvoiceCommand}> = (props) => {
          const {data} = props ?? {};

          return  createInvoice(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInvoiceMutationResult = NonNullable<Awaited<ReturnType<typeof createInvoice>>>
    export type CreateInvoiceMutationBody = CreateInvoiceCommand
    export type CreateInvoiceMutationError = unknown | ProblemDetails

    /**
 * @summary Create a single invoice for selected orders
 */
export const useCreateInvoice = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvoice>>, TError,{data: CreateInvoiceCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInvoice>>,
        TError,
        {data: CreateInvoiceCommand},
        TContext
      > => {
      return useMutation(getCreateInvoiceMutationOptions(options), queryClient);
    }
    export type createInvoicesBulkResponse200 = {
  data: IResult
  status: 200
}

export type createInvoicesBulkResponse404 = {
  data: unknown
  status: 404
}

export type createInvoicesBulkResponseDefault = {
  data: ProblemDetails
  status: Exclude<HTTPStatusCodes, 200 | 404>
}

export type createInvoicesBulkResponseSuccess = (createInvoicesBulkResponse200) & {
  headers: Headers;
};
export type createInvoicesBulkResponseError = (createInvoicesBulkResponse404 | createInvoicesBulkResponseDefault) & {
  headers: Headers;
};

export type createInvoicesBulkResponse = (createInvoicesBulkResponseSuccess | createInvoicesBulkResponseError)

export const getCreateInvoicesBulkUrl = () => {




  return `/api/invoices/bulk`
}

/**
 * POST_api_invoices_bulk
 * @summary Create multiple invoices for date range
 */
export const createInvoicesBulk = async (createInvoicesCommand: CreateInvoicesCommand, options?: RequestInit): Promise<createInvoicesBulkResponse> => {

  const res = await fetch(getCreateInvoicesBulkUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInvoicesCommand,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createInvoicesBulkResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createInvoicesBulkResponse
}




export const getCreateInvoicesBulkMutationOptions = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvoicesBulk>>, TError,{data: CreateInvoicesCommand}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createInvoicesBulk>>, TError,{data: CreateInvoicesCommand}, TContext> => {

const mutationKey = ['createInvoicesBulk'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvoicesBulk>>, {data: CreateInvoicesCommand}> = (props) => {
          const {data} = props ?? {};

          return  createInvoicesBulk(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInvoicesBulkMutationResult = NonNullable<Awaited<ReturnType<typeof createInvoicesBulk>>>
    export type CreateInvoicesBulkMutationBody = CreateInvoicesCommand
    export type CreateInvoicesBulkMutationError = unknown | ProblemDetails

    /**
 * @summary Create multiple invoices for date range
 */
export const useCreateInvoicesBulk = <TError = unknown | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvoicesBulk>>, TError,{data: CreateInvoicesCommand}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createInvoicesBulk>>,
        TError,
        {data: CreateInvoicesCommand},
        TContext
      > => {
      return useMutation(getCreateInvoicesBulkMutationOptions(options), queryClient);
    }
