/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.API | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * POST_invoices
 * @summary Create a single invoice for selected orders
 */
export const createInvoiceBodyInvoiceNumberRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const CreateInvoiceBody = zod.object({
  "invoiceNumber": zod.union([zod.number(),zod.stringFormat('int32', createInvoiceBodyInvoiceNumberRegExpTwo)]).nullable(),
  "saleDate": zod.iso.datetime({"offset":true}),
  "issueDate": zod.iso.datetime({"offset":true}),
  "dates": zod.array(zod.iso.datetime({"offset":true})),
  "orderIds": zod.array(zod.string()),
  "contractorNip": zod.string()
})

export const CreateInvoiceResponse = zod.looseObject({

})

/**
 * POST_invoices_bulk
 * @summary Create multiple invoices for date range
 */
export const CreateInvoicesBulkBody = zod.object({
  "dateFrom": zod.iso.datetime({"offset":true}),
  "dateTo": zod.iso.datetime({"offset":true})
})

export const CreateInvoicesBulkResponse = zod.looseObject({

})

