//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolcarProductsService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductRequest", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class ProductRequest : object
    {
        
        private PolcarProductsService.Product[] ListOfProductsField;
        
        private int BranchIDField;
        
        private string DistributorCodeField;
        
        private string CustomerNumberField;
        
        private string ErrorCodeField;
        
        private string ErrorInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PolcarProductsService.Product[] ListOfProducts
        {
            get
            {
                return this.ListOfProductsField;
            }
            set
            {
                this.ListOfProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DistributorCode
        {
            get
            {
                return this.DistributorCodeField;
            }
            set
            {
                this.DistributorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ErrorInformation
        {
            get
            {
                return this.ErrorInformationField;
            }
            set
            {
                this.ErrorInformationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class Product : object
    {
        
        private string PartNumberField;
        
        private string QuantityAvaliableField;
        
        private string PartNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PartNumber
        {
            get
            {
                return this.PartNumberField;
            }
            set
            {
                this.PartNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QuantityAvaliable
        {
            get
            {
                return this.QuantityAvaliableField;
            }
            set
            {
                this.QuantityAvaliableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PartName
        {
            get
            {
                return this.PartNameField;
            }
            set
            {
                this.PartNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class ProductResponse : object
    {
        
        private PolcarProductsService.Product[] ListOfProductsField;
        
        private int BranchIDField;
        
        private string ErrorCodeField;
        
        private string ErrorInformationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public PolcarProductsService.Product[] ListOfProducts
        {
            get
            {
                return this.ListOfProductsField;
            }
            set
            {
                this.ListOfProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorInformation
        {
            get
            {
                return this.ErrorInformationField;
            }
            set
            {
                this.ErrorInformationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", ConfigurationName="PolcarProductsService.ProductsSoap")]
    public interface ProductsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetStockLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsResponse> GetStockLevelsAsync(PolcarProductsService.GetStockLevelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetStockLevelsForList", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsForListResponse> GetStockLevelsForListAsync(PolcarProductsService.GetStockLevelsForListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetStockLevelsForListOfProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsForListOfProductsResponse> GetStockLevelsForListOfProductsAsync(PolcarProductsService.GetStockLevelsForListOfProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetStockLevels_eTN", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevels_eTNResponse> GetStockLevels_eTNAsync(PolcarProductsService.GetStockLevels_eTNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/UploadStockLevels", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevelsResponse> UploadStockLevelsAsync(PolcarProductsService.UploadStockLevelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/UploadStockLevelsWithReport", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevelsWithReportResponse> UploadStockLevelsWithReportAsync(PolcarProductsService.UploadStockLevelsWithReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/UploadStockLevels_eTN", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevels_eTNResponse> UploadStockLevels_eTNAsync(PolcarProductsService.UploadStockLevels_eTNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetProductsList", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetProductsListResponse> GetProductsListAsync(PolcarProductsService.GetProductsListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetProductsList_eTN", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetProductsList_eTNResponse> GetProductsList_eTNAsync(PolcarProductsService.GetProductsList_eTNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetEAN13List", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetEAN13ListResponse> GetEAN13ListAsync(PolcarProductsService.GetEAN13ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dedal.polcar.com.pl/Nemesis/WebServices/GetEAN13List_eTN", ReplyAction="*")]
        System.Threading.Tasks.Task<PolcarProductsService.GetEAN13List_eTNResponse> GetEAN13List_eTNAsync(PolcarProductsService.GetEAN13List_eTNRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevelsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevels", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevelsRequestBody Body;
        
        public GetStockLevelsRequest()
        {
        }
        
        public GetStockLevelsRequest(PolcarProductsService.GetStockLevelsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevelsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int BranchID;
        
        public GetStockLevelsRequestBody()
        {
        }
        
        public GetStockLevelsRequestBody(string Login, string Password, int BranchID)
        {
            this.Login = Login;
            this.Password = Password;
            this.BranchID = BranchID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevelsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevelsResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevelsResponseBody Body;
        
        public GetStockLevelsResponse()
        {
        }
        
        public GetStockLevelsResponse(PolcarProductsService.GetStockLevelsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevelsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetStockLevelsResult;
        
        public GetStockLevelsResponseBody()
        {
        }
        
        public GetStockLevelsResponseBody(System.Xml.XmlElement GetStockLevelsResult)
        {
            this.GetStockLevelsResult = GetStockLevelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevelsForListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevelsForList", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevelsForListRequestBody Body;
        
        public GetStockLevelsForListRequest()
        {
        }
        
        public GetStockLevelsForListRequest(PolcarProductsService.GetStockLevelsForListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevelsForListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int BranchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public System.Xml.XmlElement PartsList;
        
        public GetStockLevelsForListRequestBody()
        {
        }
        
        public GetStockLevelsForListRequestBody(string Login, string Password, int BranchID, System.Xml.XmlElement PartsList)
        {
            this.Login = Login;
            this.Password = Password;
            this.BranchID = BranchID;
            this.PartsList = PartsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevelsForListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevelsForListResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevelsForListResponseBody Body;
        
        public GetStockLevelsForListResponse()
        {
        }
        
        public GetStockLevelsForListResponse(PolcarProductsService.GetStockLevelsForListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevelsForListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetStockLevelsForListResult;
        
        public GetStockLevelsForListResponseBody()
        {
        }
        
        public GetStockLevelsForListResponseBody(System.Xml.XmlElement GetStockLevelsForListResult)
        {
            this.GetStockLevelsForListResult = GetStockLevelsForListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevelsForListOfProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevelsForListOfProducts", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevelsForListOfProductsRequestBody Body;
        
        public GetStockLevelsForListOfProductsRequest()
        {
        }
        
        public GetStockLevelsForListOfProductsRequest(PolcarProductsService.GetStockLevelsForListOfProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevelsForListOfProductsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarProductsService.ProductRequest productRequest;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int LanguageID;
        
        public GetStockLevelsForListOfProductsRequestBody()
        {
        }
        
        public GetStockLevelsForListOfProductsRequestBody(PolcarProductsService.ProductRequest productRequest, string Login, string Password, int LanguageID)
        {
            this.productRequest = productRequest;
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevelsForListOfProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevelsForListOfProductsResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevelsForListOfProductsResponseBody Body;
        
        public GetStockLevelsForListOfProductsResponse()
        {
        }
        
        public GetStockLevelsForListOfProductsResponse(PolcarProductsService.GetStockLevelsForListOfProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevelsForListOfProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PolcarProductsService.ProductResponse GetStockLevelsForListOfProductsResult;
        
        public GetStockLevelsForListOfProductsResponseBody()
        {
        }
        
        public GetStockLevelsForListOfProductsResponseBody(PolcarProductsService.ProductResponse GetStockLevelsForListOfProductsResult)
        {
            this.GetStockLevelsForListOfProductsResult = GetStockLevelsForListOfProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevels_eTNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevels_eTN", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevels_eTNRequestBody Body;
        
        public GetStockLevels_eTNRequest()
        {
        }
        
        public GetStockLevels_eTNRequest(PolcarProductsService.GetStockLevels_eTNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevels_eTNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StoreID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CredentialsGuid;
        
        public GetStockLevels_eTNRequestBody()
        {
        }
        
        public GetStockLevels_eTNRequestBody(string StoreID, string CredentialsGuid)
        {
            this.StoreID = StoreID;
            this.CredentialsGuid = CredentialsGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockLevels_eTNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockLevels_eTNResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetStockLevels_eTNResponseBody Body;
        
        public GetStockLevels_eTNResponse()
        {
        }
        
        public GetStockLevels_eTNResponse(PolcarProductsService.GetStockLevels_eTNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetStockLevels_eTNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetStockLevels_eTNResult;
        
        public GetStockLevels_eTNResponseBody()
        {
        }
        
        public GetStockLevels_eTNResponseBody(System.Xml.XmlElement GetStockLevels_eTNResult)
        {
            this.GetStockLevels_eTNResult = GetStockLevels_eTNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadStockLevelsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadStockLevels", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.UploadStockLevelsRequestBody Body;
        
        public UploadStockLevelsRequest()
        {
        }
        
        public UploadStockLevelsRequest(PolcarProductsService.UploadStockLevelsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class UploadStockLevelsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement StockLevels;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int BranchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public UploadStockLevelsRequestBody()
        {
        }
        
        public UploadStockLevelsRequestBody(System.Xml.XmlElement StockLevels, int BranchID, string Login, string Password)
        {
            this.StockLevels = StockLevels;
            this.BranchID = BranchID;
            this.Login = Login;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadStockLevelsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadStockLevelsResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.UploadStockLevelsResponseBody Body;
        
        public UploadStockLevelsResponse()
        {
        }
        
        public UploadStockLevelsResponse(PolcarProductsService.UploadStockLevelsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class UploadStockLevelsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadStockLevelsResult;
        
        public UploadStockLevelsResponseBody()
        {
        }
        
        public UploadStockLevelsResponseBody(string UploadStockLevelsResult)
        {
            this.UploadStockLevelsResult = UploadStockLevelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadStockLevelsWithReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadStockLevelsWithReport", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.UploadStockLevelsWithReportRequestBody Body;
        
        public UploadStockLevelsWithReportRequest()
        {
        }
        
        public UploadStockLevelsWithReportRequest(PolcarProductsService.UploadStockLevelsWithReportRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class UploadStockLevelsWithReportRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement StockLevels;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int BranchID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password;
        
        public UploadStockLevelsWithReportRequestBody()
        {
        }
        
        public UploadStockLevelsWithReportRequestBody(System.Xml.XmlElement StockLevels, int BranchID, string Login, string Password)
        {
            this.StockLevels = StockLevels;
            this.BranchID = BranchID;
            this.Login = Login;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadStockLevelsWithReportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadStockLevelsWithReportResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.UploadStockLevelsWithReportResponseBody Body;
        
        public UploadStockLevelsWithReportResponse()
        {
        }
        
        public UploadStockLevelsWithReportResponse(PolcarProductsService.UploadStockLevelsWithReportResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class UploadStockLevelsWithReportResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement UploadStockLevelsWithReportResult;
        
        public UploadStockLevelsWithReportResponseBody()
        {
        }
        
        public UploadStockLevelsWithReportResponseBody(System.Xml.XmlElement UploadStockLevelsWithReportResult)
        {
            this.UploadStockLevelsWithReportResult = UploadStockLevelsWithReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadStockLevels_eTNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadStockLevels_eTN", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.UploadStockLevels_eTNRequestBody Body;
        
        public UploadStockLevels_eTNRequest()
        {
        }
        
        public UploadStockLevels_eTNRequest(PolcarProductsService.UploadStockLevels_eTNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class UploadStockLevels_eTNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement StockLevels;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StoreID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CredentialsGuid;
        
        public UploadStockLevels_eTNRequestBody()
        {
        }
        
        public UploadStockLevels_eTNRequestBody(System.Xml.XmlElement StockLevels, string StoreID, string CredentialsGuid)
        {
            this.StockLevels = StockLevels;
            this.StoreID = StoreID;
            this.CredentialsGuid = CredentialsGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadStockLevels_eTNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadStockLevels_eTNResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.UploadStockLevels_eTNResponseBody Body;
        
        public UploadStockLevels_eTNResponse()
        {
        }
        
        public UploadStockLevels_eTNResponse(PolcarProductsService.UploadStockLevels_eTNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class UploadStockLevels_eTNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadStockLevels_eTNResult;
        
        public UploadStockLevels_eTNResponseBody()
        {
        }
        
        public UploadStockLevels_eTNResponseBody(string UploadStockLevels_eTNResult)
        {
            this.UploadStockLevels_eTNResult = UploadStockLevels_eTNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsList", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetProductsListRequestBody Body;
        
        public GetProductsListRequest()
        {
        }
        
        public GetProductsListRequest(PolcarProductsService.GetProductsListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetProductsListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int LanguageID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int FormatID;
        
        public GetProductsListRequestBody()
        {
        }
        
        public GetProductsListRequestBody(string Login, string Password, int LanguageID, int FormatID)
        {
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
            this.FormatID = FormatID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsListResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetProductsListResponseBody Body;
        
        public GetProductsListResponse()
        {
        }
        
        public GetProductsListResponse(PolcarProductsService.GetProductsListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetProductsListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetProductsListResult;
        
        public GetProductsListResponseBody()
        {
        }
        
        public GetProductsListResponseBody(System.Xml.XmlElement GetProductsListResult)
        {
            this.GetProductsListResult = GetProductsListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsList_eTNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsList_eTN", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetProductsList_eTNRequestBody Body;
        
        public GetProductsList_eTNRequest()
        {
        }
        
        public GetProductsList_eTNRequest(PolcarProductsService.GetProductsList_eTNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetProductsList_eTNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LanguageID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FormatID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CredentialsGuid;
        
        public GetProductsList_eTNRequestBody()
        {
        }
        
        public GetProductsList_eTNRequestBody(int LanguageID, int FormatID, string CredentialsGuid)
        {
            this.LanguageID = LanguageID;
            this.FormatID = FormatID;
            this.CredentialsGuid = CredentialsGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsList_eTNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsList_eTNResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetProductsList_eTNResponseBody Body;
        
        public GetProductsList_eTNResponse()
        {
        }
        
        public GetProductsList_eTNResponse(PolcarProductsService.GetProductsList_eTNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetProductsList_eTNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetProductsList_eTNResult;
        
        public GetProductsList_eTNResponseBody()
        {
        }
        
        public GetProductsList_eTNResponseBody(System.Xml.XmlElement GetProductsList_eTNResult)
        {
            this.GetProductsList_eTNResult = GetProductsList_eTNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEAN13ListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEAN13List", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetEAN13ListRequestBody Body;
        
        public GetEAN13ListRequest()
        {
        }
        
        public GetEAN13ListRequest(PolcarProductsService.GetEAN13ListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetEAN13ListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int LanguageID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int FormatID;
        
        public GetEAN13ListRequestBody()
        {
        }
        
        public GetEAN13ListRequestBody(string Login, string Password, int LanguageID, int FormatID)
        {
            this.Login = Login;
            this.Password = Password;
            this.LanguageID = LanguageID;
            this.FormatID = FormatID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEAN13ListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEAN13ListResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetEAN13ListResponseBody Body;
        
        public GetEAN13ListResponse()
        {
        }
        
        public GetEAN13ListResponse(PolcarProductsService.GetEAN13ListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetEAN13ListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetEAN13ListResult;
        
        public GetEAN13ListResponseBody()
        {
        }
        
        public GetEAN13ListResponseBody(System.Xml.XmlElement GetEAN13ListResult)
        {
            this.GetEAN13ListResult = GetEAN13ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEAN13List_eTNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEAN13List_eTN", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetEAN13List_eTNRequestBody Body;
        
        public GetEAN13List_eTNRequest()
        {
        }
        
        public GetEAN13List_eTNRequest(PolcarProductsService.GetEAN13List_eTNRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetEAN13List_eTNRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LanguageID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FormatID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CredentialsGuid;
        
        public GetEAN13List_eTNRequestBody()
        {
        }
        
        public GetEAN13List_eTNRequestBody(int LanguageID, int FormatID, string CredentialsGuid)
        {
            this.LanguageID = LanguageID;
            this.FormatID = FormatID;
            this.CredentialsGuid = CredentialsGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEAN13List_eTNResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEAN13List_eTNResponse", Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices", Order=0)]
        public PolcarProductsService.GetEAN13List_eTNResponseBody Body;
        
        public GetEAN13List_eTNResponse()
        {
        }
        
        public GetEAN13List_eTNResponse(PolcarProductsService.GetEAN13List_eTNResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dedal.polcar.com.pl/Nemesis/WebServices")]
    public partial class GetEAN13List_eTNResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetEAN13List_eTNResult;
        
        public GetEAN13List_eTNResponseBody()
        {
        }
        
        public GetEAN13List_eTNResponseBody(System.Xml.XmlElement GetEAN13List_eTNResult)
        {
            this.GetEAN13List_eTNResult = GetEAN13List_eTNResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ProductsSoapChannel : PolcarProductsService.ProductsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ProductsSoapClient : System.ServiceModel.ClientBase<PolcarProductsService.ProductsSoap>, PolcarProductsService.ProductsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductsSoapClient.GetBindingForEndpoint(endpointConfiguration), ProductsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsResponse> PolcarProductsService.ProductsSoap.GetStockLevelsAsync(PolcarProductsService.GetStockLevelsRequest request)
        {
            return base.Channel.GetStockLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsResponse> GetStockLevelsAsync(string Login, string Password, int BranchID)
        {
            PolcarProductsService.GetStockLevelsRequest inValue = new PolcarProductsService.GetStockLevelsRequest();
            inValue.Body = new PolcarProductsService.GetStockLevelsRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.BranchID = BranchID;
            return ((PolcarProductsService.ProductsSoap)(this)).GetStockLevelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsForListResponse> PolcarProductsService.ProductsSoap.GetStockLevelsForListAsync(PolcarProductsService.GetStockLevelsForListRequest request)
        {
            return base.Channel.GetStockLevelsForListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsForListResponse> GetStockLevelsForListAsync(string Login, string Password, int BranchID, System.Xml.XmlElement PartsList)
        {
            PolcarProductsService.GetStockLevelsForListRequest inValue = new PolcarProductsService.GetStockLevelsForListRequest();
            inValue.Body = new PolcarProductsService.GetStockLevelsForListRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.BranchID = BranchID;
            inValue.Body.PartsList = PartsList;
            return ((PolcarProductsService.ProductsSoap)(this)).GetStockLevelsForListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsForListOfProductsResponse> PolcarProductsService.ProductsSoap.GetStockLevelsForListOfProductsAsync(PolcarProductsService.GetStockLevelsForListOfProductsRequest request)
        {
            return base.Channel.GetStockLevelsForListOfProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetStockLevelsForListOfProductsResponse> GetStockLevelsForListOfProductsAsync(PolcarProductsService.ProductRequest productRequest, string Login, string Password, int LanguageID)
        {
            PolcarProductsService.GetStockLevelsForListOfProductsRequest inValue = new PolcarProductsService.GetStockLevelsForListOfProductsRequest();
            inValue.Body = new PolcarProductsService.GetStockLevelsForListOfProductsRequestBody();
            inValue.Body.productRequest = productRequest;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            return ((PolcarProductsService.ProductsSoap)(this)).GetStockLevelsForListOfProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetStockLevels_eTNResponse> PolcarProductsService.ProductsSoap.GetStockLevels_eTNAsync(PolcarProductsService.GetStockLevels_eTNRequest request)
        {
            return base.Channel.GetStockLevels_eTNAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetStockLevels_eTNResponse> GetStockLevels_eTNAsync(string StoreID, string CredentialsGuid)
        {
            PolcarProductsService.GetStockLevels_eTNRequest inValue = new PolcarProductsService.GetStockLevels_eTNRequest();
            inValue.Body = new PolcarProductsService.GetStockLevels_eTNRequestBody();
            inValue.Body.StoreID = StoreID;
            inValue.Body.CredentialsGuid = CredentialsGuid;
            return ((PolcarProductsService.ProductsSoap)(this)).GetStockLevels_eTNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevelsResponse> PolcarProductsService.ProductsSoap.UploadStockLevelsAsync(PolcarProductsService.UploadStockLevelsRequest request)
        {
            return base.Channel.UploadStockLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevelsResponse> UploadStockLevelsAsync(System.Xml.XmlElement StockLevels, int BranchID, string Login, string Password)
        {
            PolcarProductsService.UploadStockLevelsRequest inValue = new PolcarProductsService.UploadStockLevelsRequest();
            inValue.Body = new PolcarProductsService.UploadStockLevelsRequestBody();
            inValue.Body.StockLevels = StockLevels;
            inValue.Body.BranchID = BranchID;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            return ((PolcarProductsService.ProductsSoap)(this)).UploadStockLevelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevelsWithReportResponse> PolcarProductsService.ProductsSoap.UploadStockLevelsWithReportAsync(PolcarProductsService.UploadStockLevelsWithReportRequest request)
        {
            return base.Channel.UploadStockLevelsWithReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevelsWithReportResponse> UploadStockLevelsWithReportAsync(System.Xml.XmlElement StockLevels, int BranchID, string Login, string Password)
        {
            PolcarProductsService.UploadStockLevelsWithReportRequest inValue = new PolcarProductsService.UploadStockLevelsWithReportRequest();
            inValue.Body = new PolcarProductsService.UploadStockLevelsWithReportRequestBody();
            inValue.Body.StockLevels = StockLevels;
            inValue.Body.BranchID = BranchID;
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            return ((PolcarProductsService.ProductsSoap)(this)).UploadStockLevelsWithReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevels_eTNResponse> PolcarProductsService.ProductsSoap.UploadStockLevels_eTNAsync(PolcarProductsService.UploadStockLevels_eTNRequest request)
        {
            return base.Channel.UploadStockLevels_eTNAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.UploadStockLevels_eTNResponse> UploadStockLevels_eTNAsync(System.Xml.XmlElement StockLevels, string StoreID, string CredentialsGuid)
        {
            PolcarProductsService.UploadStockLevels_eTNRequest inValue = new PolcarProductsService.UploadStockLevels_eTNRequest();
            inValue.Body = new PolcarProductsService.UploadStockLevels_eTNRequestBody();
            inValue.Body.StockLevels = StockLevels;
            inValue.Body.StoreID = StoreID;
            inValue.Body.CredentialsGuid = CredentialsGuid;
            return ((PolcarProductsService.ProductsSoap)(this)).UploadStockLevels_eTNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetProductsListResponse> PolcarProductsService.ProductsSoap.GetProductsListAsync(PolcarProductsService.GetProductsListRequest request)
        {
            return base.Channel.GetProductsListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetProductsListResponse> GetProductsListAsync(string Login, string Password, int LanguageID, int FormatID)
        {
            PolcarProductsService.GetProductsListRequest inValue = new PolcarProductsService.GetProductsListRequest();
            inValue.Body = new PolcarProductsService.GetProductsListRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            inValue.Body.FormatID = FormatID;
            return ((PolcarProductsService.ProductsSoap)(this)).GetProductsListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetProductsList_eTNResponse> PolcarProductsService.ProductsSoap.GetProductsList_eTNAsync(PolcarProductsService.GetProductsList_eTNRequest request)
        {
            return base.Channel.GetProductsList_eTNAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetProductsList_eTNResponse> GetProductsList_eTNAsync(int LanguageID, int FormatID, string CredentialsGuid)
        {
            PolcarProductsService.GetProductsList_eTNRequest inValue = new PolcarProductsService.GetProductsList_eTNRequest();
            inValue.Body = new PolcarProductsService.GetProductsList_eTNRequestBody();
            inValue.Body.LanguageID = LanguageID;
            inValue.Body.FormatID = FormatID;
            inValue.Body.CredentialsGuid = CredentialsGuid;
            return ((PolcarProductsService.ProductsSoap)(this)).GetProductsList_eTNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetEAN13ListResponse> PolcarProductsService.ProductsSoap.GetEAN13ListAsync(PolcarProductsService.GetEAN13ListRequest request)
        {
            return base.Channel.GetEAN13ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetEAN13ListResponse> GetEAN13ListAsync(string Login, string Password, int LanguageID, int FormatID)
        {
            PolcarProductsService.GetEAN13ListRequest inValue = new PolcarProductsService.GetEAN13ListRequest();
            inValue.Body = new PolcarProductsService.GetEAN13ListRequestBody();
            inValue.Body.Login = Login;
            inValue.Body.Password = Password;
            inValue.Body.LanguageID = LanguageID;
            inValue.Body.FormatID = FormatID;
            return ((PolcarProductsService.ProductsSoap)(this)).GetEAN13ListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolcarProductsService.GetEAN13List_eTNResponse> PolcarProductsService.ProductsSoap.GetEAN13List_eTNAsync(PolcarProductsService.GetEAN13List_eTNRequest request)
        {
            return base.Channel.GetEAN13List_eTNAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolcarProductsService.GetEAN13List_eTNResponse> GetEAN13List_eTNAsync(int LanguageID, int FormatID, string CredentialsGuid)
        {
            PolcarProductsService.GetEAN13List_eTNRequest inValue = new PolcarProductsService.GetEAN13List_eTNRequest();
            inValue.Body = new PolcarProductsService.GetEAN13List_eTNRequestBody();
            inValue.Body.LanguageID = LanguageID;
            inValue.Body.FormatID = FormatID;
            inValue.Body.CredentialsGuid = CredentialsGuid;
            return ((PolcarProductsService.ProductsSoap)(this)).GetEAN13List_eTNAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductsSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://dedal.polcar.com/Dystrybutorzy/Products.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://dedal.polcar.com/Dystrybutorzy/Products.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProductsSoap,
            
            ProductsSoap12,
        }
    }
}
