/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApplicationHealthResponse,
  ApplicationVersionResponse,
  HttpValidationProblemDetails
} from '../models';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApplicationVersionUrl = () => {




  return `/api/version`
}

/**
 * @summary Get the running application version information.
 */
export const getApplicationVersion = async ( options?: RequestInit): Promise<ApplicationVersionResponse> => {

  return customFetch<ApplicationVersionResponse>(getGetApplicationVersionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApplicationVersionQueryKey = () => {
    return [
    `/api/version`
    ] as const;
    }


export const getGetApplicationVersionQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationVersion>>, TError = HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationVersion>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationVersionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationVersion>>> = ({ signal }) => getApplicationVersion({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationVersion>>>
export type GetApplicationVersionQueryError = HttpValidationProblemDetails


export function useGetApplicationVersion<TData = Awaited<ReturnType<typeof getApplicationVersion>>, TError = HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationVersion>>,
          TError,
          Awaited<ReturnType<typeof getApplicationVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationVersion<TData = Awaited<ReturnType<typeof getApplicationVersion>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationVersion>>,
          TError,
          Awaited<ReturnType<typeof getApplicationVersion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationVersion<TData = Awaited<ReturnType<typeof getApplicationVersion>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationVersion>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the running application version information.
 */

export function useGetApplicationVersion<TData = Awaited<ReturnType<typeof getApplicationVersion>>, TError = HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationVersion>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationVersionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApplicationHealthUrl = () => {




  return `/api/health`
}

/**
 * @summary Get the application health status.
 */
export const getApplicationHealth = async ( options?: RequestInit): Promise<ApplicationHealthResponse> => {

  return customFetch<ApplicationHealthResponse>(getGetApplicationHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApplicationHealthQueryKey = () => {
    return [
    `/api/health`
    ] as const;
    }


export const getGetApplicationHealthQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationHealth>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationHealth>>> = ({ signal }) => getApplicationHealth({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationHealth>>>
export type GetApplicationHealthQueryError = ApplicationHealthResponse | HttpValidationProblemDetails


export function useGetApplicationHealth<TData = Awaited<ReturnType<typeof getApplicationHealth>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationHealth>>,
          TError,
          Awaited<ReturnType<typeof getApplicationHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationHealth<TData = Awaited<ReturnType<typeof getApplicationHealth>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationHealth>>,
          TError,
          Awaited<ReturnType<typeof getApplicationHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationHealth<TData = Awaited<ReturnType<typeof getApplicationHealth>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the application health status.
 */

export function useGetApplicationHealth<TData = Awaited<ReturnType<typeof getApplicationHealth>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationHealth>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApplicationAlivenessUrl = () => {




  return `/api/alive`
}

/**
 * @summary Get the application liveness status.
 */
export const getApplicationAliveness = async ( options?: RequestInit): Promise<ApplicationHealthResponse> => {

  return customFetch<ApplicationHealthResponse>(getGetApplicationAlivenessUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApplicationAlivenessQueryKey = () => {
    return [
    `/api/alive`
    ] as const;
    }


export const getGetApplicationAlivenessQueryOptions = <TData = Awaited<ReturnType<typeof getApplicationAliveness>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationAliveness>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationAlivenessQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplicationAliveness>>> = ({ signal }) => getApplicationAliveness({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplicationAliveness>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApplicationAlivenessQueryResult = NonNullable<Awaited<ReturnType<typeof getApplicationAliveness>>>
export type GetApplicationAlivenessQueryError = ApplicationHealthResponse | HttpValidationProblemDetails


export function useGetApplicationAliveness<TData = Awaited<ReturnType<typeof getApplicationAliveness>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationAliveness>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationAliveness>>,
          TError,
          Awaited<ReturnType<typeof getApplicationAliveness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationAliveness<TData = Awaited<ReturnType<typeof getApplicationAliveness>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationAliveness>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplicationAliveness>>,
          TError,
          Awaited<ReturnType<typeof getApplicationAliveness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApplicationAliveness<TData = Awaited<ReturnType<typeof getApplicationAliveness>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationAliveness>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the application liveness status.
 */

export function useGetApplicationAliveness<TData = Awaited<ReturnType<typeof getApplicationAliveness>>, TError = ApplicationHealthResponse | HttpValidationProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplicationAliveness>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApplicationAlivenessQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






