/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedErrorsRouteImport } from './routes/_protected/errors'
import { Route as ProtectedContractorsRouteImport } from './routes/_protected/contractors'

const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedErrorsRoute = ProtectedErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedContractorsRoute = ProtectedContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/contractors': typeof ProtectedContractorsRoute
  '/errors': typeof ProtectedErrorsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/contractors': typeof ProtectedContractorsRoute
  '/errors': typeof ProtectedErrorsRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/_protected/contractors': typeof ProtectedContractorsRoute
  '/_protected/errors': typeof ProtectedErrorsRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/pending-approval' | '/contractors' | '/errors'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/pending-approval' | '/contractors' | '/errors' | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/pending-approval'
    | '/_protected/contractors'
    | '/_protected/errors'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/errors': {
      id: '/_protected/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ProtectedErrorsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contractors': {
      id: '/_protected/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof ProtectedContractorsRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedContractorsRoute: typeof ProtectedContractorsRoute
  ProtectedErrorsRoute: typeof ProtectedErrorsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedContractorsRoute: ProtectedContractorsRoute,
  ProtectedErrorsRoute: ProtectedErrorsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
