$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Path $PSScriptRoot -Parent
$outputPath = Join-Path $repoRoot ".env.example"

$includeExtensions = @(".cs", ".ts", ".tsx", ".txt")
$excludePathParts = @("/.git/", "/bin/", "/obj/", "/node_modules/", "/dist/", "/Logs/")
$tagPattern = [regex]"@env:\s*(?<key>[^=\s]+)=(?<value>.*)$"

$entries = foreach ($file in Get-ChildItem -Path $repoRoot -Recurse -File) {
	if ($includeExtensions -notcontains $file.Extension) {
		continue
	}

	$normalizedPath = $file.FullName.Replace('\', '/')
	if ($excludePathParts | Where-Object { $normalizedPath.Contains($_, [System.StringComparison]::OrdinalIgnoreCase) }) {
		continue
	}

	$lines = Get-Content -Path $file.FullName
	for ($index = 0; $index -lt $lines.Count; $index++) {
		$trimmedLine = $lines[$index].TrimStart()
		if (-not ($trimmedLine.StartsWith("// @env:") -or $trimmedLine.StartsWith("# @env:"))) {
			continue
		}

		$match = $tagPattern.Match($trimmedLine)
		if (-not $match.Success) {
			continue
		}

		$key = $match.Groups["key"].Value.Trim()
		$defaultValue = $match.Groups["value"].Value.Trim()
		$sourcePath = [System.IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')

		[pscustomobject]@{
			Key = $key
			DefaultValue = $defaultValue
			SourcePath = $sourcePath
			LineNumber = $index + 1
		}
	}
}

$duplicates = $entries | Group-Object Key | Where-Object { $_.Count -gt 1 }
if ($duplicates) {
	$duplicateMessage = $duplicates | ForEach-Object {
		$locations = $_.Group | ForEach-Object { "  - $($_.SourcePath):$($_.LineNumber)" }
		"Duplicate key $($_.Name)`n$($locations -join "`n")"
	}

	throw ($duplicateMessage -join "`n`n")
}

$orderedEntries = $entries | Sort-Object SourcePath, LineNumber
$content = New-Object System.Text.StringBuilder
[void]$content.AppendLine("# Generated by scripts/generate-env-example.ps1. Do not edit by hand.")
[void]$content.AppendLine()

$currentSource = $null
foreach ($entry in $orderedEntries) {
	if ($entry.SourcePath -ne $currentSource) {
		if ($null -ne $currentSource) {
			[void]$content.AppendLine()
		}

		$currentSource = $entry.SourcePath
		[void]$content.AppendLine("# Source: $currentSource")
	}

	[void]$content.AppendLine("$($entry.Key)=$($entry.DefaultValue)")
}

[System.IO.File]::WriteAllText($outputPath, $content.ToString().TrimEnd() + [System.Environment]::NewLine)
Write-Host "Generated $outputPath with $($orderedEntries.Count) entries"
