/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * @summary Create a single invoice for selected orders
 */
export const createInvoiceBodyInvoiceNumberRegExpTwo = /^-?(?:0|[1-9]\d*)$/;

export const CreateInvoiceBody = zod.object({
	invoiceNumber: zod
		.union([zod.number(), zod.stringFormat("int32", createInvoiceBodyInvoiceNumberRegExpTwo)])
		.nullable(),
	saleDate: zod.iso.date(),
	issueDate: zod.iso.date(),
	dates: zod.array(zod.iso.datetime({ offset: true })),
	orderIds: zod.array(zod.string()),
	contractorNIP: zod.string(),
});

/**
 * @summary Create an invoice from manually provided items
 */
export const createManualInvoiceBodyInvoiceNumberRegExpTwo = /^-?(?:0|[1-9]\d*)$/;
export const createManualInvoiceBodyItemsItemQuantityRegExpTwo = /^-?(?:0|[1-9]\d*)$/;
export const createManualInvoiceBodyItemsItemNetUnitPriceRegExpTwo = /^-?(?:0|[1-9]\d*)(?:\.\d+)?$/;

export const CreateManualInvoiceBody = zod.object({
	invoiceNumber: zod
		.union([zod.number(), zod.stringFormat("int32", createManualInvoiceBodyInvoiceNumberRegExpTwo)])
		.nullable(),
	saleDate: zod.iso.date(),
	issueDate: zod.iso.date(),
	contractorNIP: zod.string(),
	items: zod.array(
		zod.object({
			itemNumber: zod.string(),
			quantity: zod.union([zod.number(), zod.stringFormat("int32", createManualInvoiceBodyItemsItemQuantityRegExpTwo)]),
			netUnitPrice: zod.union([
				zod.number(),
				zod.stringFormat("double", createManualInvoiceBodyItemsItemNetUnitPriceRegExpTwo),
			]),
		}),
	),
});
