/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Autodor.OpenApi | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Include or exclude order from invoicing
 */
export const UpdateOrderExclusionParams = zod.object({
  "id": zod.string()
})

export const UpdateOrderExclusionBody = zod.object({
  "id": zod.string().optional(),
  "excluded": zod.boolean().optional()
})

/**
 * @summary Get order by ID and date
 */
export const GetOrderParams = zod.object({
  "id": zod.string()
})

export const GetOrderQueryParams = zod.object({
  "date": zod.iso.datetime({"offset":true})
})

export const getOrderResponseItemsItemQuantityRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const getOrderResponseItemsItemPriceRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');


export const GetOrderResponse = zod.object({
  "id": zod.string(),
  "number": zod.string().nullable(),
  "date": zod.iso.datetime({"offset":true}),
  "person": zod.string().nullable(),
  "customerNumber": zod.string().nullable(),
  "items": zod.array(zod.object({
  "productDisplayName": zod.string(),
  "quantity": zod.union([zod.number(),zod.stringFormat('int32', getOrderResponseItemsItemQuantityRegExpTwo)]),
  "price": zod.union([zod.number(),zod.stringFormat('double', getOrderResponseItemsItemPriceRegExpTwo)]),
  "isExcluded": zod.boolean()
})),
  "isExcluded": zod.boolean()
})

/**
 * @summary Include or exclude order item from invoicing
 */
export const UpdateOrderItemExclusionParams = zod.object({
  "id": zod.string(),
  "itemNumber": zod.string()
})

export const UpdateOrderItemExclusionBody = zod.object({
  "id": zod.string().optional(),
  "itemNumber": zod.string().optional(),
  "excluded": zod.boolean().optional()
})

/**
 * @summary Generate PDF delivery note for an order
 */
export const GenerateDeliveryNoteBody = zod.object({
  "orderId": zod.string().optional(),
  "date": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get all orders within date range
 */
export const GetOrdersQueryParams = zod.object({
  "from": zod.iso.datetime({"offset":true}),
  "to": zod.iso.datetime({"offset":true})
})

export const getOrdersResponseOrdersItemItemsCountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');
export const getOrdersResponseOrdersItemTotalAmountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)(?:\\.\\d+)?$');
export const getOrdersResponseOrdersItemExcludedItemsCountRegExpTwo = new RegExp('^-?(?:0|[1-9]\\d\*)$');


export const GetOrdersResponse = zod.object({
  "orders": zod.array(zod.object({
  "id": zod.string(),
  "number": zod.string().nullable(),
  "date": zod.iso.datetime({"offset":true}),
  "person": zod.string().nullable(),
  "customerNumber": zod.string().nullable(),
  "itemsCount": zod.union([zod.number(),zod.stringFormat('int32', getOrdersResponseOrdersItemItemsCountRegExpTwo)]),
  "totalAmount": zod.union([zod.number(),zod.stringFormat('double', getOrdersResponseOrdersItemTotalAmountRegExpTwo)]),
  "isExcluded": zod.boolean(),
  "excludedItemsCount": zod.union([zod.number(),zod.stringFormat('int32', getOrdersResponseOrdersItemExcludedItemsCountRegExpTwo)])
}))
})

