name: Deploy app

run-name: Deploy app from ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches: [main, slice]
    paths:
      - 'apps/app/Dockerfile'
      - 'apps/app/**'
      - '.github/workflows/app.yml'
      - '.github/workflows/_deploy-service.yml'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service_name: app
      image_name: autodor-app
      image_file: ./apps/app/Dockerfile
      webhook_secret_names_json: '["WEBHOOK_URL_APP_MTP","WEBHOOK_URL_APP_DOR"]'
      build_arg_secret_name: VITE_CLERK_PUBLISHABLE_KEY
    secrets: inherit
